# Introducción a la terminal

## Formato del post

Para no tener que estar poniendo imágenes de la consola en cada acción que haga, he creado la siguiente función que recibe el comando de la terminal que queramos ejecutar y devuelve la salida que nos daría la terminal.

Unas veces usaré esta función, y otras usaré `!` antes de cada comando, que en notebooks quiere decir que vas a ejecutar un comando de la terminal.

In [ ]:
import subprocess
import os

last_directory = ''

def terminal(command, max_lines_output=None):
    global last_directory
    debug = False
    str = command.split()

    # Check if there are " or ' characters
    for i in range(len(str)):
        if debug:   print(f"i = {i}, str[i] = {str[i]}")
        if len(str[i]) > 0:
            if str[i][0] == '"' or str[i][0] == "'":
                for j in range(i+1,len(str)):
                    if debug:   print(f"\t j = {j}, str[j] = {str[j]}")
                    if str[j][-1] == '"' or str[j][-1] == "'":
                        for k in range(i+1,j+1):
                            if debug:   print(f"\t\t k = {k}, str[i] = {str[i]}, str[k] = {str[k]}")
                            str[i] = str[i] + " " + str[k]
                            if debug:   print(f"\t\t k = {k}, str[i] = {str[i]}, str[k] = {str[k]}")
                        str[j:] = [""]
                        str[i] = str[i].replace('"','')

    # Remove empty strings
    str = [x for x in str if x != ""]
    if debug:
        print(str)
        return
    if str[0] == "cd":
        last_dir = os.getcwd()
        if len(str) == 1:
            os.chdir('/home/wallabot')
        else:
            if str[1] == "-":
                os.chdir(last_directory)
            else:
                os.chdir(str[1])
        last_directory = last_dir
    else:
        result = subprocess.run(str, stdout=subprocess.PIPE).stdout.decode('utf-8')
        if max_lines_output is not None:
            result_split = result.split('\n')
            print('\n'.join(result_split[:max_lines_output]))
            print("\t ...")
            print('\n'.join(result_split[-5:]))
        else:
            print(result)

## Primeros comandos para moverse por la terminal

### `ls` (list directory)

El primer comando que vamos a ver es `ls` (list directory) que sirve para listar todos los archivos de la carpeta en la que estemos.

In [ ]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
ssh.ipynb
test.html
test.ipynb



Los comandos normalmente pueden recibir opciones (`flags`), que se introducen con el carácter `-`, por ejemplo veamos `ls -l` que nos devuelve la lista de archivos del directorio en el que estamos, pero con más información

In [ ]:
terminal('ls -l')

total 4512
-rw-rw-r-- 1 wallabot wallabot 285898 nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  78450 nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 484213 nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 320810 dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 320594 dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 119471 oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot   2660 sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 699225 nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 509125 sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 156193 nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  53094 oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 wallabot wallabot   4096 nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  1

Como vemos, tenemos cuántos bytes ocupa cada archivo, pero cuando tenemos archivos que ocupan mucho esto no es muy fácil de leer, así que podemos añadir la opción `h` (`human`) que nos da información más fácil de leer

In [ ]:
terminal('ls -lh')

total 4,5M
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  15K sep 18 03:29 html.ipy

Si queremos ver los archivos ocultos podemos usar la opción `a`, que nos mostrará todos los archivos de un directorio

In [ ]:
terminal('ls -lha')

total 4,5M
drwxrwxr-x 6 wallabot wallabot 4,0K dic  6 00:04 .
drwxrwxr-x 5 wallabot wallabot 4,0K oct  2 03:10 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 w

Si lo que queremos es que nos los ordene por tamaño, podemos usar la opción `S`

In [ ]:
terminal('ls -lhS')

total 4,5M
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 510K oct  2 04:33 movies.dat
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 436K oct  2 04:39 movies.csv
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 287K nov  9 01:46 test.html
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot 255K nov  9 01:13 test.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 w

Si queremos que nos muestre los archivos ordenados alfabéticamente, pero al revés, debemos usar la opción `-r`

In [ ]:
terminal('ls -lhr')

total 4,5M
-rw-rw-r-- 1 wallabot wallabot 255K nov  9 01:13 test.ipynb
-rw-rw-r-- 1 wallabot wallabot 287K nov  9 01:46 test.html
-rw-rw-r-- 1 wallabot wallabot  586 dic  4 02:31 ssh.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K ago 27 03:25 __pycache__
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 notebooks_translated
-rw-rw-r-- 1 wallabot wallabot 510K oct  2 04:33 movies.dat
-rw-rw-r-- 1 wallabot wallabot 436K oct  2 04:39 movies.csv
drwxrwxr-x 3 wallabot wallabot 4,0K nov 12 01:51 introduccion_python
-rw-rw-r-- 1 wallabot wallabot  15K sep 18 03:29 html.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 117K 

### `cd` (change directory)

El segundo comando será `cd` (change directory) que nos permite cambiar de directorio

In [ ]:
terminal('cd /home/wallabot/Documentos/')

Si ahora volvemos a usar `ls` para ver los archivos que tenemos, vemos que cambian

In [ ]:
terminal('ls')

aprendiendo-git.pdf
balena-etcher-electron-1.7.9-linux-x64
camerasIP
Documentacion
gstreamer
gstreamer_old
jetsonNano
kaggle
Libros
nerf
prueba.txt
pytorch
wallabot
web



Si a `cd`, en vez de darle el directorio al que nos queremos mover, le damos el carácter `-`, volverá al anterior directorio donde estaba

In [ ]:
terminal('cd -')

In [ ]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
ssh.ipynb
test.html
test.ipynb



Si nos quisiéramos mover a la `home` con introducir solamente `cd` en la terminal nos llevará.

In [ ]:
terminal('cd')

### `pwd` (print working directory)

Para obtener el directorio en el que estamos, podemos usar `pwd` (print working directory)

In [ ]:
terminal('pwd')

/home/wallabot



Podemos movernos mediante el comando `cd` mediante rutas relativas y mediante rutas absolutas. Por ejemplo, vamos a movernos a un directorio mediante una ruta absoluta.

In [ ]:
terminal('cd /home/wallabot/Documentos/')

In [ ]:
terminal('pwd')

/home/wallabot/Documentos



In [ ]:
terminal('ls')

aprendiendo-git.pdf
balena-etcher-electron-1.7.9-linux-x64
camerasIP
Documentacion
gstreamer
gstreamer_old
jetsonNano
kaggle
Libros
nerf
prueba.txt
pytorch
wallabot
web



Podemos movernos mediante rutas relativas si solo ponemos la dirección a partir del punto en que nos encontramos

In [ ]:
terminal('cd web')

In [ ]:
terminal('pwd')

/home/wallabot/Documentos/web



También mediante rutas relativas podemos ir un directorio arriba mediante `..`

In [ ]:
terminal('cd ..')

In [ ]:
terminal('pwd')

/home/wallabot/Documentos



Si en vez de `..` ponemos `.` nos estamos refiriendo al directorio en el que nos encontramos ahora mismo, es decir, si ponemos `cd .` no nos moveremos, ya que le estamos diciendo a la terminal que vaya al directorio en el que estamos.

In [ ]:
terminal('cd .')

In [ ]:
terminal('pwd')

/home/wallabot/Documentos



Vamos a movernos a una ruta en la que tengamos archivos para mostrar el siguiente comando

In [ ]:
terminal('cd web/portafolio/posts/')

In [ ]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
ssh.ipynb
test.html
test.ipynb



### Información de archivos con `file`

Si yo no sé qué tipo de archivo es alguno en particular, mediante el comando `file` puedo obtener una descripción

In [ ]:
terminal('file 2021-02-11-Introduccion-a-Python.ipynb')

2021-02-11-Introduccion-a-Python.ipynb: UTF-8 Unicode text, with very long lines



## Manipulando archivos y directorios

Movámonos primero a la home.

In [ ]:
terminal('cd /home/wallabot/Documentos/')

### Árbol de directorios con `tree`

Podemos ver toda la estructura de la carpeta en la que estamos mediante el comando `tree`

In [ ]:
terminal('tree', max_lines_output=20)

.
├── aprendiendo-git.pdf
├── balena-etcher-electron-1.7.9-linux-x64
│   └── balenaEtcher-1.7.9-x64.AppImage
├── camerasIP
│   ├── camerasIP.py
│   ├── camerasIP.sh
│   ├── config.py
│   ├── __pycache__
│   │   ├── config.cpython-38.pyc
│   │   └── config.cpython-39.pyc
│   └── README.md
├── Documentacion
│   ├── Curriculum Vitae (5).pdf
│   ├── Firma Pris.PNG
│   └── Firma.png
├── gstreamer
│   ├── basic_tutorial_c
│   │   ├── basic_tutorial_1_hello_world
│   │   │   ├── basic-tutorial-1
	 ...
        ├── upload_page.py
        └── utils.py

873 directories, 119679 files



Pero a la salida tenemos demasiadas líneas, y esto es porque `tree` es un comando que muestra todos los archivos desde la ruta en la que estamos, por lo que es un poco difícil de leer. Sin embargo, con la opción `L` podemos indicarle en cuántos niveles queremos que profundice

In [ ]:
terminal('tree -L 2')

.
├── aprendiendo-git.pdf
├── balena-etcher-electron-1.7.9-linux-x64
│   └── balenaEtcher-1.7.9-x64.AppImage
├── camerasIP
│   ├── camerasIP.py
│   ├── camerasIP.sh
│   ├── config.py
│   ├── __pycache__
│   └── README.md
├── Documentacion
│   ├── Curriculum Vitae (5).pdf
│   ├── Firma Pris.PNG
│   └── Firma.png
├── gstreamer
│   ├── basic_tutorial_c
│   └── README.md
├── gstreamer_old
│   ├── basic_tutorial_c
│   └── basic_tutorial_python
├── jetsonNano
│   ├── apuntes-Jetson-Nano
│   ├── deepstream_apps
│   ├── deepstream_nano
│   └── Digital zoom
├── kaggle
│   └── hubmap
├── Libros
│   └── aprendiendo-git.pdf
├── nerf
│   └── instant-ngp
├── prueba.txt
├── pytorch
│   └── Curso_Pytorch
├── wallabot
│   ├── Microfono - Blue Yeti X
│   ├── placa base - Asus prime x570-p
│   └── Silla - Corsair T3 Rush
└── web
    ├── jupyter-to-html
    ├── jupyter-translator
    ├── portafolio
    └── wordpress_api_rest

30 directories, 12 files



Podemos ver que muestra que hay 30 directorios y 12 archivos, mientras que antes indicaba 873 directorios, 119679 archivos

### Crear carpetas con `mkdir` (make directory)

Si queremos crear un nuevo directorio podemos usar el comando `mkdir` (make directory) y un nombre

In [ ]:
terminal("cd /home/wallabot/Documentos/web/portafolio/posts/")

In [ ]:
terminal('mkdir prueba')

In [ ]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Si lo que queremos es crear un directorio con espacios en el nombre, tenemos que poner el nombre entre comillas.

In [ ]:
terminal('mkdir "directorio prueba"')

In [ ]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
directorio prueba
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Vamos a meternos dentro de la carpeta `prueba` que hemos creado, para seguir viendo allí la terminal

In [ ]:
terminal("cd prueba")

### Crear archivos con `touch`

En caso de que queramos crear un archivo, el comando que tenemos que usar es `touch`

In [ ]:
terminal("touch prueba.txt")

In [ ]:
terminal("ls")

prueba.txt



### Copiar archivos con `cp` (copy)

Si queremos copiar un archivo lo hacemos mediante el comando `cp` (copy)

In [ ]:
terminal("cp prueba.txt prueba_copy.txt")

In [ ]:
terminal("ls")

prueba_copy.txt
prueba.txt



### Mover archivos con `mv` (move)

Si lo que queremos es moverlo, lo que usamos es el comando `mv` (move)

In [ ]:
terminal("mv prueba.txt ../prueba.txt")

In [ ]:
terminal("ls")

prueba_copy.txt



In [ ]:
terminal("ls ../")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
directorio prueba
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
prueba.txt
__pycache__
ssh.ipynb
test.html
test.ipynb



### Renombrar archivos con `mv` (move)

El comando `mv` también nos sirve para renombrar ficheros, ya que si lo que hacemos es moverlo en el mismo directorio, pero dándole otro nombre, al final eso es renombrar el archivo.

In [ ]:
terminal("mv prueba_copy.txt prueba_move.txt")

In [ ]:
terminal("ls")

prueba_move.txt



### Borrar archivos con `rm` (remove)

Para borrar archivos o directorios usamos el comando `rm` (remove)

In [ ]:
terminal("rm prueba_move.txt")

In [ ]:
terminal("ls")

### Eliminar directorios con `rm -r` (remove recursive)

Si lo que queremos es eliminar un directorio con archivos dentro, debemos usar el flag `-r`.

In [ ]:
terminal("cd ..")

In [ ]:
terminal('rm -r "directorio prueba"')

In [ ]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
prueba.txt
__pycache__
ssh.ipynb
test.html
test.ipynb



Como puedes ver nunca pregunta si estamos seguros, para que pregunte hay que añadir el flag `-i` (`iteractive`)

In [ ]:
terminal("rm -i prueba.txt")

rm: ¿borrar el fichero regular vacío 'prueba.txt'? (s/n) s



### Sincronizar archivos mediante `rsync`

Hasta ahora hemos visto cómo copiar, mover y eliminar archivos, pero supongamos que tenemos una carpeta y copiamos esos archivos a otra. Ahora supongamos que modificamos un archivo de la primera carpeta y queremos que la segunda tenga los cambios. Tenemos dos opciones, volver a copiar todos los archivos, o hacer una sincronización mediante `rsync`

Primero vamos a crear una nueva carpeta en la que creemos varios archivos

In [ ]:
!mkdir sourcefolder
!touch sourcefolder/file1 sourcefolder/file2 sourcefolder/file3

Ahora creamos una segunda carpeta que es la que vamos a sincronizar con la primera

In [ ]:
!mkdir syncfolder

In [ ]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3
ls syncfolder:


Sincronizamos las dos carpetas con `rsync`, la primera vez solo copiará los archivos de la primera carpeta a la segunda. Para hacer esto, además debemos añadir el flag `-r` (recursive)

In [ ]:
!rsync -r sourcefolder/ syncfolder/

In [ ]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3
ls syncfolder:
file1  file2  file3


Si ahora creo un nuevo archivo en `sourcefolder` y vuelvo a sincronizar, se copia solo ese archivo en `syncfolder`. Para ver que solo se copia un archivo podemos usar el flag `-v` (verbose)

In [ ]:
!touch sourcefolder/file4

In [ ]:
!rsync -r -v sourcefolder/ syncfolder/

sending incremental file list
file1
file2
file3
file4

sent 269 bytes  received 92 bytes  722.00 bytes/sec
total size is 0  speedup is 0.00


Pero parece que ha copiado todos los archivos, así que para que esto no pase y copie solo los que se han modificado hay que usar el flag `-u`

In [ ]:
!touch sourcefolder/file5

In [ ]:
!rsync -r -v -u sourcefolder/ syncfolder/

sending incremental file list
file5

sent 165 bytes  received 35 bytes  400.00 bytes/sec
total size is 0  speedup is 0.00


In [ ]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3  file4  file5
ls syncfolder:
file1  file2  file3  file4  file5


¿Y qué pasa si creo un archivo nuevo en `syncfolder`?

In [ ]:
!touch syncfolder/file6

In [ ]:
!rsync -r -v -u sourcefolder/ syncfolder/

sending incremental file list

sent 122 bytes  received 12 bytes  268.00 bytes/sec
total size is 0  speedup is 0.00


In [ ]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3  file4  file5
ls syncfolder:
file1  file2  file3  file4  file5  file6


No lo sincroniza, así que es importante tener esto en cuenta

Algunos flags importantes que hay que tener en cuenta son:

 * `-a`: Este flag es un atajo para varias opciones, incluyendo `-r` (recursivo), `-l` (copiar enlaces simbólicos), `-p` (mantener permisos), `-t` (mantener la hora de modificación) y `-g` (mantener grupo). Esta opción es útil para hacer una copia exacta de un directorio, incluyendo todas sus subcarpetas y archivos.
 * `-v`: Este flag activa la salida detallada, que muestra los archivos que se están copiando y el progreso de la operación.
 * `-r`: Este flag es utilizado para copiar de forma recursiva, lo que significa que copia todas las subcarpetas y archivos dentro de un directorio.
 * `-u`: Este flag es utilizado para copiar solo los archivos nuevos o modificados. Si un archivo ya existe en el destino y es más reciente que el archivo de origen, no se copia.
 * `-n`: Este flag se utiliza para hacer una prueba de copia, lo que significa que no se realizan cambios en el destino.
 * `--exclude`: Este flag se utiliza para excluir archivos o carpetas específicos de la operación de copia. Puedes especificar varios archivos o carpetas para excluir utilizando esta opción varias veces.
 * `-z`: Este flag se utiliza para comprimir los datos durante la transferencia, lo que reduce el ancho de banda utilizado y acelera la velocidad de transferencia.
* `-h`: este flag se usa para mostrar la información en un formato más legible, especialmente cuando se trabaja con grandes cantidades de datos o tamaños de archivos grandes.

Borramos las dos carpetas creadas

In [ ]:
!rm -r sourcefolder syncfolder


## Explorando el contenido de los archivos

Para no tener que abrir un archivo desde una interfaz gráfica tenemos varias formas. Voy a copiar un archivo de texto en esta carpeta lo primero.

In [ ]:
terminal("cd prueba")

In [ ]:
terminal("cp ../2021-02-11-Introduccion-a-Python.ipynb .")

In [ ]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb



### Cabecera de archivos con `head`

El primer comando para poder ver dentro de un archivo de texto es `head`, que nos permite ver las primeras 10 líneas de un archivo, pero si se le mete el flag `-n` puedes indicar el número de líneas

In [ ]:
terminal("head 2021-02-11-Introduccion-a-Python.ipynb")

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]



In [ ]:
terminal("head -n 5 2021-02-11-Introduccion-a-Python.ipynb")

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {



### Cola de un archivo con `tail`

En caso de querer ver las últimas líneas usamos `tail`

In [ ]:
terminal("tail 2021-02-11-Introduccion-a-Python.ipynb")

    },
    "vscode": {
      "interpreter": {
        "hash": "d5745ab6aba164e1152437c779991855725055592b9f2bdb41a4825db7168d26"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



In [ ]:
terminal("tail -n 5 2021-02-11-Introduccion-a-Python.ipynb")

    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



Si queremos ver continuamente las últimas líneas de un archivo, por ejemplo, queremos estar monitorizando continuamente un archivo de LOG para ver eventos, añadimos el flag `-f`, esto hará que la terminal se quede continuamente comprobando el archivo, y cada vez que aparezca una nueva línea en él la mostrará

Por ejemplo si yo monitoreo el log de inicio de sesión en mi máquina

In [ ]:
!tail -f /var/log/auth.log

Dec  1 16:27:22 wallabot gcr-prompter[1457]: Gcr: calling the PromptDone method on /org/gnome/keyring/Prompt/p2@:1.26, and ignoring reply
Dec  1 16:27:22 wallabot gnome-keyring-daemon[1178]: asked to register item /org/freedesktop/secrets/collection/login/10, but it's already registered
Dec  1 16:27:26 wallabot systemd-logind[835]: Watching system buttons on /dev/input/event28 (Logitech Wireless Mouse MX Master 3)
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: 10 second inactivity timeout, quitting
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: unregistering prompter
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: disposing prompter
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: finalizing prompter
Dec  1 16:27:34 wallabot polkitd(authority=local): Operator of unix-session:1 successfully authenticated as unix-user:wallabot to gain TEMPORARY authorization for action org.debian.apt.install-or-remove-packages for system-bus-name::1.96 [/usr/bin/python3 /usr/bin/update-manager -

Vemos en las dos últimas líneas mi inicio de sesión cuando he encendido hoy mi ordenador.

Ahora me conecto por SSH a mi propia máquina

In [ ]:
!ssh localhost

wallabot@localhost's password: 
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-53-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

1 device has a firmware upgrade available.
Run `fwupdmgr get-upgrades` for more information.


Se pueden aplicar 0 actualizaciones de forma inmediata.

Your Hardware Enablement Stack (HWE) is supported until April 2025.
*** System restart required ***
Last login: Sun May  8 02:18:09 2022 from 192.168.1.147


En la consola donde estaba monitorizando el inicio de sesión han aparecido dos nuevas líneas

Dec  1 16:32:23 wallabot sshd[25647]: Accepted password for wallabot from 127.0.0.1 port 54668 ssh2
Dec  1 16:32:23 wallabot sshd[25647]: pam_unix(sshd:session): session opened for user wallabot by (uid=0)
Dec  1 16:32:23 wallabot systemd-logind[835]: New session 4 of user wallabot.


Y cuando cierro la sesión SSH aparecen otras dos líneas nuevas

Dec  1 16:33:52 wallabot sshd[25647]: pam_unix(sshd:session): session closed for user wallabot
Dec  1 16:33:52 wallabot systemd-logind[835]: Session 4 logged out. Waiting for processes to exit.
Dec  1 16:33:52 wallabot systemd-logind[835]: Removed session 4.


### El visor de archivos más potente: `less`

Uno de los comandos más potentes para ver dentro de los archivos es `less`

In [ ]:
terminal("less 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Ho_8zgIiI0We"
      },
      "source": [
        "## 1. Resumen"
      ]
    },
	 ...
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



Al estar dentro de un cuaderno no se puede ver lo que ocurre realmente al usar `less`, pero cuando lo usamos nos metemos en el documento, podemos movernos a través de él mediante las teclas, o con el ratón

Si queremos buscar algo dentro del documento, escribimos el carácter `/` y lo que queramos buscar. Para cambiar entre las distintas instancias que ha encontrado pulsamos la tecla `n`, y si queremos volver hacia atrás en las búsquedas pulsamos `shift+n`

Para salir solo hay que pulsar `q`

### El visor `cat`

No te permite navegar por el archivo ni hacer búsquedas.

In [ ]:
terminal("cat 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Ho_8zgIiI0We"
      },
      "source": [
        "## 1. Resumen"
      ]
    },
	 ...
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



### Editor por defecto del sistema `xdg-open`

Si lo queremos abrir con el editor por defecto del archivo, tenemos que usar `xdg-open`

In [ ]:
terminal("xdg-open 2021-02-11-Introducción-a-Python.ipynb")

### Navegador de archivos `nautilus`

Si lo que queremos es abrir la carpeta en la que estamos, usamos `nautilus`

In [ ]:
terminal("nautilus")

Y si lo que queremos es que se abra en una ruta determinada, se incluye la ruta

In [ ]:
terminal("nautilus ~/")

### Contador de palabras de un archivo con `wc` (word count)

Por último, un comando muy útil es `wc` (word count), que te muestra cuántas líneas, palabras y bytes tiene un archivo

In [ ]:
terminal("wc 2021-02-11-Introduccion-a-Python.ipynb")

 11678  25703 285898 2021-02-11-Introduccion-a-Python.ipynb



Como vemos, el archivo tiene 11678 líneas, 25703 palabras y ocupa 285898 bytes

## Qué es un comando

Un comando puede ser cuatro cosas
* Un programa ejecutable, éstos normalmente se guardan en la ruta `/usr/bin`
 * Un comando de shell
 * Una función de shell
 * Un alias

Para ver a qué clase pertenece un comando usamos `type`

In [ ]:
!type cd

cd is a shell builtin


In [ ]:
!type mkdir

mkdir is /usr/bin/mkdir


In [ ]:
!type ls

ls is /usr/bin/ls


## ¿Qué es un alias?

Un alias es un comando que definimos nosotros, este se define mediante el comando `alias`. Por ejemplo, vamos a crear el alias `l` que lo que haga sea `ls -h`

In [ ]:
!alias l='ls -l'

Cuando ejecutamos `l` nos muestra el resultado de `ls -h`

In [ ]:
!l

2021-02-11-Introducción-a-Python.ipynb


Pero esto tiene el problema, que cuando cerremos la terminal desaparece el `alias`. Más adelante aprenderemos a crear `alias` permanentes

## Ayuda de los comandos

### Ayuda con `help`

Con muchos comandos de la shell, podemos obtener su ayuda mediante el comando `help`

In [ ]:
!help cd

cd: cd [-L|[-P [-e]]] [dir]
    Modifica el directorio de trabajo del shell.
    
    Modifica el directorio actual a DIR.  DIR por defecto es el valor de la
    variable de shell HOME.
    
    La variable CDPATH define la ruta de búsqueda para el directorio que
    contiene DIR.  Los nombres alternativos de directorio en CDPATH se
    separan con dos puntos (:).  Un nombre de directorio nulo es igual que
    el directorio actual.  Si DIR comienza con una barra inclinada (/),
    entonces no se usa CDPATH.
    
    Si no se encuentra el directorio, y la opción del shell "cdable_vars"
    está activa, entonces se trata la palabra como un nombre de variable.
    Si esa variable tiene un valor, se utiliza su valor para DIR.
    
    Opciones:
      -L	fuerza a seguir los enlaces simbólicos: resuelve los enlaces
    		simbólicos en DIR después de procesar las instancias de ".."
      -P	usa la estructura física de directorios sin seguir los enlaces
    		simbólicos: resuelve los enlaces s

### Manual con `man`

Otro comando es `man`, que hace referencia al manual de usuario.

In [ ]:
terminal("man ls", max_lines_output=20)

LS(1)                            User Commands                           LS(1)

NAME
       ls - list directory contents

SYNOPSIS
       ls [OPTION]... [FILE]...

DESCRIPTION
       List  information  about  the FILEs (the current directory by default).
       Sort entries alphabetically if none of -cftuvSUX nor --sort  is  speci‐
       fied.

       Mandatory  arguments  to  long  options are mandatory for short options
       too.

       -a, --all
              do not ignore entries starting with .

       -A, --almost-all
	 ...
       Full documentation at: <https://www.gnu.org/software/coreutils/ls>
       or available locally via: info '(coreutils) ls invocation'

GNU coreutils 8.30              September 2019                           LS(1)



Para salir, pulsar `q`, ya que `man` utiliza a `less` como visualizador del manual

### Información con `info`

Otro comando es `info`

In [ ]:
terminal("info ls", max_lines_output=20)

File: coreutils.info,  Node: ls invocation,  Next: dir invocation,  Up: Directory listing

10.1 ‘ls’: List directory contents

The ‘ls’ program lists information about files (of any type, including
directories).  Options and file arguments can be intermixed arbitrarily,
as usual.

   For non-option command-line arguments that are directories, by
default ‘ls’ lists the contents of directories, not recursively, and
omitting files with names beginning with ‘.’.  For other non-option
arguments, by default ‘ls’ lists just the file name.  If no non-option
argument is specified, ‘ls’ operates on the current directory, acting as
if it had been invoked with a single argument of ‘.’.

   By default, the output is sorted alphabetically, according to the
locale settings in effect.(1)  If standard output is a terminal, the
output is in columns (sorted vertically) and control characters are
output as question marks; otherwise, the output is listed one per line
	 ...
‘--show-control-chars’
     Print

Para salir, pulsar `q`, ya que `info` utiliza a `less` como visualizador de la información

### Información de un comando con `whatis`

Otro comando es `whatis`

In [ ]:
terminal("whatis ls")

ls (1)               - list directory contents



## Wildcards

Las wildcards son caracteres especiales que nos sirven para realizar búsquedas especiales. Por ejemplo, si quiero buscar todos los archivos que terminen en `.txt`. Vamos a crear unos cuantos archivos para verlas.

In [ ]:
terminal("touch file.txt dot.txt dot2.txt index.html datos1 datos123 Abc")

In [ ]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html



### Todos los caracteres `*`

Vamos a buscar ahora todos los archivos `.txt`

In [ ]:
!ls *.txt

dot2.txt  dot.txt  file.txt


Vamos ahora a buscar todos los que empiecen por la palabra `datos`

In [ ]:
!ls datos*

datos1	datos123


### Números `?`

Pero qué pasa si en realidad lo que queremos es que nos muestre todos los archivos que empiecen por la palabra `datos` pero seguido solo de un número, tenemos que poner un signo de interrogación `?`

In [ ]:
!ls datos?

datos1


Si lo que queremos es que tenga tres números, entonces tenemos que poner tres signos de interrogación `???`

In [ ]:
!ls datos???

datos123


### Mayúsculas `[[:upper:]]`

Si queremos que busque los archivos que empiecen por mayúsculas

In [ ]:
!ls [[:upper:]]*

Abc


### Minúsculas `[[:lower:]]`

Para los archivos que empiecen con minúsculas.

In [ ]:
!ls [[:lower:]]*

datos1  datos123  dot2.txt  dot.txt  file.txt  index.html


### Clases

Mediante el uso de corchetes podemos crear clases, así si queremos buscar los archivos que empiecen por las letras `d` o `f` seguido de cualquier carácter

In [ ]:
!ls [df]*

datos1  datos123  dot2.txt  dot.txt  file.txt


## Redirecciones: cómo funciona la shell

Un comando funciona de la siguiente manera

![pipeline comando](https://ptgmedia.pearsoncmg.com/images/chap5_9780133927313/elementLinks/05fig02_alt.jpg)

Tiene un `standard input`, que por defecto es el texto que introducimos por teclado, un `standard output`, que por defecto es el texto que sale por consola y un `standard error` que también es por defecto un texto que sale por consola, pero que tiene otro formato

### Redirección del `standard output`

Pero con el carácter `>` podemos modificar el `standard output` de un comando. Por ejemplo, si queremos listar con `ls` los archivos de la carpeta en la que estamos, pero no queremos que el resultado se imprima por pantalla, sino que se guarde en un archivo, haríamos lo siguiente `ls > lista.txt`, esto escribe la lista en `lista.txt`, además si `lista.txt` no existe, lo crea

In [ ]:
!ls > lista.txt

Vemos que ha creado el archivo y vemos qué hay dentro

In [ ]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



In [ ]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



Vemos que dentro de `lista.txt` aparece `lista.txt`, eso es porque primero crea el archivo y luego ejecuta el comando

Hacemos lo mismo, pero con la carpeta padre

In [ ]:
!ls ../ > lista.txt

Si volvemos a ver dentro de `lista.txt`

In [ ]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Vemos que se sobreescribe el contenido

Si lo que queremos es que se concatene el contenido, debemos usar `>>`

In [ ]:
!ls > lista.txt

In [ ]:
!ls ../ >> lista.txt

In [ ]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt
2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Ahora sí se ha concatenado la información

Esto es muy útil para crear archivos de log

### Redirección del `standard error`

Si realizamos una operación incorrecta obtenemos un error, veamos qué pasa al redireccionar un comando que da un error

In [ ]:
!ls fjhdsalkfs > lista.txt

ls: no se puede acceder a 'fjhdsalkfs': No existe el archivo o el directorio


Como vemos, ha dado un error, pero si ahora vemos dentro de `lista.txt`

In [ ]:
terminal("cat lista.txt")

Vemos que el archivo está vacío, eso es porque no hemos redireccionado el `standard error` a `lista.txt`, sino el `standard output`. Como hemos visto en la imagen, hay dos standards de salida en un comando, el primero es el `standard output` y el segundo el `standard error`, por lo que para redireccionar el standard error hay que indicarlo mediante `2>`. Vamos ahora así

In [ ]:
!ls kjhsfskjd 2> lista.txt

In [ ]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio



Como vemos ahora sí se ha redireccionado

### Redirección del `standard output` y del `standard error`

Si queremos redirigir los dos usamos lo siguiente

In [ ]:
!ls kjhsfskjd > lista.txt 2>&1

Veamos dentro de `lista.txt`

In [ ]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio



Si ahora ejecutamos un comando sin errores

In [ ]:
!ls . >> lista.txt 2>&1

Veamos dentro de `lista.txt` (**ojo**, ahora hemos concatenado)

In [ ]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio
2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



Como se puede ver, se han redirigido, tanto el `standard error`, como el `standard output` al mismo archivo

## Pipelines

Podemos crear pipelines haciendo que el `standard output` de un comando se convierta en el `standard input` de otro. Por ejemplo, vamos a hacer que la salida de `ls -lha` sea la entrada de `grep`, que lo veremos más adelante, pero es un comando para buscar.

In [ ]:
!ls -lha |  grep -i "txt"

-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt


Como podemos ver, lo que hemos hecho ha sido llevar la salida de `ls` a `grep` con el que hemos buscado algún archivo con `txt` en el nombre

## Operadores de control - encadenar comandos

### Comandos de manera secuencial

Una forma de encadenar comandos de forma secuencial es separarlos mediante `;`. Esto crea diferentes hilos para cada tarea

In [ ]:
!ls; echo 'Hola'; cal

2021-02-11-Introduccion-a-Python.ipynb	datos123  file.txt
Abc					dot2.txt  index.html
datos1					dot.txt   lista.txt
Hola
   Diciembre 2022     
do lu ma mi ju vi sá  
             1  2  3  
 4  5  6  7  8  9 10  
11 12 13 14 15 16 17  
18 19 20 21 22 23 24  
25 26 27 28 29 30 31  
                      


Como podemos ver, primero se ha ejecutado el comando `ls`, luego se ha impreso Hola gracias al comando `echo "Hola"` y por último se ha impreso un calendario gracias al comando `cal`

Vamos ahora a hacer otro ejemplo para ver que se ejecutan de manera secuencial.

In [ ]:
!echo "Before touch;"; ls -lha; touch secuential.txt; echo "After touch:"; ls -lha

Before touch;
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:04 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:07 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-

Como se puede ver, en el primer `ls` no aparece `secuential.txt`, mientras que en el segundo sí. Eso quiere decir que los comandos se han ejecutado en orden, uno detrás de otro

### Comandos de manera paralela

Si lo que queremos es que los comandos se ejecuten de manera paralela hay que usar el operador `&`, esto hará que se cree un nuevo proceso por cada comando

Veamos el ejemplo de antes

In [ ]:
!rm secuential.txt

In [ ]:
!echo "Before touch;" & ls -lha & touch secuential.txt & echo "After touch:" & ls -lha

Before touch;
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt


Ahora se puede ver que no se han ejecutado secuencialmente, ya que primero se han ejecutado los `echo`s, que serán los que menos tarden, y después el resto

### Comandos de manera condicional

#### And

Utilizando el operador `&&`, un comando se ejecutará cuando el anterior se haya ejecutado satisfactoriamente

In [ ]:
!rm secuential.txt

In [ ]:
!echo "Before touch;" && ls -lha && touch secuential.txt && echo "After touch:" && ls -lha

Before touch;
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-

Aquí podemos ver cómo se ha ejecutado uno detrás de otro, es decir, un comando no empieza hasta que el anterior acaba

Pero entonces, ¿cuál es la diferencia entre `;` y `&&`?

En el primero, el secuencial `;`, primero se ejecuta un comando y luego otro, pero para que se ejecute un comando da igual que el anterior se haya ejecutado satisfactoriamente

In [ ]:
!rm prueba ; ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt


Como se puede ver primero se ejecuta `rm prueba`, da un error y aun así se ejecuta `ls -lha prueba`

En la manera condicional `&&`, si un comando no se ejecuta satisfactoriamente, el siguiente no se ejecuta.

In [ ]:
!rm prueba && ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio


Como se puede ver `ls -lha prueba` no se ejecuta ya que `rm prueba` ha dado un error

#### Or

A diferencia del `&&`, el 'or' ejecutará todos los procesos sea cual sea su resultado. Se ha de utilizar el operador `||`

In [ ]:
!rm prueba || ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt


La diferencia entre este y `;` es que el `||` (or) no crea un nuevo hilo para cada comando

## Cómo se manejan los permisos

Cuando se listan los archivos de un directorio con el flag `-l` (long) aparecen unos símbolos al lado de cada archivo.

In [ ]:
!mkdir subdirectorio

In [ ]:
!ls -l

total 288
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 dic  6 01:10 subdirectorio


Esto nos da información de cada archivo

Primero veamos qué tipos de archivos hay
 * -: Archivo normal
 * d: Directorio
* l: Link simbólico
* b: Archivo de bloque especial. Son archivos que manejan la información de los bloques de datos como, por ejemplo, un USB

Después veremos los tipos de modo:

<table border="1">
	<header>
		<tr>
<th scope="col" colspan="3">Dueño</th>
			<th scope="col" colspan="3">Grupo</th>
<th scope="col" colspan="3">World</th>
		</tr>
	</header>
	<body>
		<tr>
<th scope="row" colspan="3">rwx</th>
			<th scope="row" colspan="3">r-x</th>
			<th scope="row" colspan="3">r-x</th>
		</tr>
		<tr>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">0</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">0</th>
			<th scope="row">1</th>
		</tr>
		<tr>
			<th scope="row" colspan="3">7</th>
			<th scope="row" colspan="3">5</th>
			<th scope="row" colspan="3">5</th>
		</tr>
	<body>
</table>

 * r: read
* w: write
 * x: execute

Modo simbólico:
 * u: Solo para el usuario
* g: Sólo para el grupo
* o: Sólo para otros (world)
 * a: Para todos

## Modificando los permisos en la terminal

Creamos un nuevo archivo

In [ ]:
terminal("cd subdirectorio")

In [ ]:
!echo "hola mundo" > mitexto.txt

In [ ]:
!cat mitexto.txt

hola mundo


Vamos a ver los permisos que tiene.

In [ ]:
!ls -l

total 4
-rw-rw-r-- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


Como vemos, tiene permisos de lectura y escritura para mi usuario y el grupo, y solo permisos de lectura para el resto (world)

### Cambio de permisos con `chmod` (change mode)

Para cambiar los permisos de un archivo usamos el comando `chmod` (change mode), donde tenemos que poner en octal los permisos del usuario, luego los del grupo y por último los del resto.

In [ ]:
!chmod 755 mitexto.txt

In [ ]:
!ls -l

total 4
-rwxr-xr-x 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


Vemos que ahora mi usuario tiene permisos de lectura, escritura y ejecución, mientras que el grupo y el resto del mundo tiene permisos de lectura y ejecución

Vamos a quitar los permisos de lectura solo a mi usuario. Para cambiar solo los permisos de un usuario usamos el identificador simbólico, un `+` si queremos agregar permisos o un `-` si queremos quitarlos o un `=` si queremos restablecerlos y seguido del tipo de permiso

In [ ]:
!chmod u-r mitexto.txt

In [ ]:
!ls -l

total 4
--wxr-xr-x 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


In [ ]:
!cat mitexto.txt

cat: mitexto.txt: Permiso denegado


Como vemos, al quitar permisos de lectura para mi usuario, no podemos leer el archivo.

Le volvemos a poner el permiso de lectura

In [ ]:
!chmod u+r mitexto.txt

In [ ]:
!ls -l

total 4
-rwxr-xr-x 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


In [ ]:
!cat mitexto.txt

hola mundo


Si queremos agregar o quitar permisos a más de un usuario, lo hacemos separando cada permiso por una `,`

In [ ]:
!chmod u-x,go=w mitexto.txt

In [ ]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


Como se puede ver, se le ha quitado el permiso de ejecución al usuario y se ha establecido el permiso de solo escritura para el grupo y el resto del mundo.

### Identificación de usuario con `whoami`

Para saber quiénes somos podemos usar el comando `whoami` (who am I)

In [ ]:
!whoami

wallabot


### Información de usuario con `id`

Otra manera, que además da más información, es el comando `id`

In [ ]:
!id

uid=1000(wallabot) gid=1000(wallabot) grupos=1000(wallabot),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare),998(docker)


Este comando nos dice que nuestro ID de usuario es el 1000, el ID de grupo es el 1000 y que pertenecemos a los grupos wallabot, adm, cdrom, sudo, dip, plugdev, lpadmin, lxd, sambashare y docker

### Cambio de usuario con el comando `su` (switch user)

Si queremos cambiar de usuario usamos el comando `su` (switch user). Para según qué usuario hay que usar `sudo` (superuser do)

In [ ]:
!sudo su root

root@wallabot:/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio#


Como vemos cambia el `prompt` y ahora indica que somos el usuario `root`

Vamos a la carpeta home

In [ ]:
!cd

root@wallabot:~#


Pero en Linux hay una carpeta home por cada usuario, esto lo podemos ver si ejecutamos el comando `pwd`

In [ ]:
!pwd

/root


Voy a crear un archivo en la carpeta donde antes he creado el archivo *mitexto.txt*

In [ ]:
!touch /home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt

Vuelvo a cambiarme a mi usuario

In [ ]:
!su wallabot

wallabot@wallabot:


Y me voy al directorio donde están los archivos que he creado.

In [ ]:
!cd /home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio

Vemos los archivos que hay y sus permisos

In [ ]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt
-rw-r--r-- 1 root     root      0 dic  6 01:22 rootfile.txt


Como vemos, el usuario y el grupo del archivo *rootfile.txt* es el usuario `root`

Si yo, ahora que soy el usuario *wallabot*, intento borrar el archivo `rootfile.txt`

In [ ]:
!rm rootfile.txt

rm: ¿borrar el fichero regular vacío 'rootfile.txt'  protegido contra escritura? (s/n)


Como vemos, nos pregunta si lo queremos borrar, ya que pertenece a otro usuario.

## Modificar la contraseña de un usuario

Si quiero modificar la contraseña del usuario que tengo actualmente activo, uso el comando `passwd` (password)

Primero compruebo qué usuario soy

In [ ]:
!whoami

wallabot


Y ahora probamos a cambiar la contraseña

In [ ]:
!passwd

$ passwd
Cambiando la contraseña de wallabot.
Contraseña actual de : 
Nueva contraseña: 
Vuelva a escribir la nueva contraseña


Como vemos, pide la actual contraseña para poder cambiarla

## Links simbólicos

Podemos crear links simbólicos a una ruta determinada mediante el comando `ln` (link) seguido del flag `-s` (symbolic), el directorio y el nombre del link

In [ ]:
!ln -s /home/wallabot/Documentos/web web

Si ahora listamos los archivos

In [ ]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt
-rw-r--r-- 1 root     root      0 dic  6 01:22 rootfile.txt
lrwxrwxrwx 1 wallabot wallabot 29 dic  6 01:28 web -> /home/wallabot/Documentos/web


Vemos el link simbólico `web` que apunta a `/home/wallabot/Documentos/web:`

Yo ahora me puedo ir a `web`

In [ ]:
terminal("cd web")

In [ ]:
!pwd

/home/wallabot/Documentos/web


## Configurar las variables de entorno

### Ver las variables de entorno con `printenv`

Con el comando `printenv` podemos ver todas las variables de entorno

In [ ]:
!printenv

GJS_DEBUG_TOPICS=JS ERROR;JS LOG
VSCODE_CWD=/home/wallabot
LESSOPEN=| /usr/bin/lesspipe %s
CONDA_PROMPT_MODIFIER=(base) 
PYTHONIOENCODING=utf-8
USER=wallabot
VSCODE_NLS_CONFIG={"locale":"es","availableLanguages":{"*":"es"},"_languagePackId":"b07c40c9acb9e1d7b3ca14b06f814803.es","_translationsConfigFile":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/tcf.json","_cacheRoot":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es","_resolvedLanguagePackCoreLocation":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/6261075646f055b99068d3688932416f2346dd3b","_corruptedFile":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/corrupted.info","_languagePackSupport":true}
VSCODE_HANDLES_UNCAUGHT_ERRORS=true
MPLBACKEND=module://ipykernel.pylab.backend_inline
SSH_AGENT_PID=1373
XDG_SESSION_TYPE=x11
SHLVL=0
HOME=/home/wallabot
CHROME_DESKTOP=code-url-handler.desktop
CONDA_SHLVL=1
DESKTOP_SESSION=ubuntu
GIO_LAUNCHED_DESKTOP_FI

### Ver una variable de entorno con el comando `echo`

Para ver una variable de entorno en concreto podemos hacerlo mediante el comando `echo` seguido del símbolo `$` y el nombre de la variable

In [ ]:
!echo $HOME

/home/wallabot


### Modificar una variable de entorno para una sesión de terminal

Podemos modificar una variable de entorno para la sesión activa de terminal, por ejemplo, vamos a agregar una nueva ruta a la variable `PATH`. Primero vemos qué hay en ella

In [ ]:
!echo $PATH

/home/wallabot/anaconda3/bin:/home/wallabot/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


Ahora añadimos un nuevo directorio

In [ ]:
!PATH=$PATH:"subdirectorio

Volvemos a ver qué hay dentro de `PATH`

In [ ]:
!echo $PATH

/home/wallabot/anaconda3/bin:/home/wallabot/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:subdirectorio


Vemos que se ha añadido el directorio `subdirectorio`.

El problema de este método es que cuando abramos una nueva terminal no se mantendrá este cambio en `PATH`

### Modificar una variable de entorno para todas las sesiones de terminal

Nos vamos a la carpeta home

In [ ]:
terminal("cd /home/wallabot")

Aquí en el home listamos todos los archivos con el flag `-a` (all)

In [ ]:
!ls -a

.		.eclipse		       .pki
..		Escritorio		       Plantillas
.afirma		.gitconfig		       .platformio
anaconda3	.gnupg			       .profile
.audacity-data	Imágenes		       .psensor
.bash_history	.ipython		       Público
.bash_logout	.java			       .python_history
.bashrc		.jupyter		       snap
.cache		.lesshst		       .ssh
.conda		Lightworks		       .sudo_as_admin_successful
.config		.Lightworks.thereCanBeOnlyOne  .thunderbird
.cortex-debug	.local			       Vídeos
.cyberghost	logiops			       .vnc
.dbus		.MCTranscodingSDK	       .vscode
Descargas	.mozilla		       .wget-hsts
.docker		Música
Documentos	.nv


Vemos que hay un archivo que se llama `.bashrc`, este archivo es el archivo que tiene la configuración de nuestro bash

In [ ]:
terminal("cat .bashrc", max_lines_output=3)

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
	 ...
fi
unset __conda_setup
# <<< conda initialize <<<




Este archivo es el que configura la terminal cada vez que se abre una nueva, por lo que si en él editamos la variable `PATH`, este cambio se mantendrá para todas las ventanas nuevas de terminal que abramos

Para modificar la variable `PATH` dentro del archivo de configuración tenemos que agregar la siguiente línea al archivo

```
PATH=$PATH:"subdirectorio"
```

### Crear alias para todas las sesiones

Ya vimos cómo crear alias de comandos, pero también pasaba que se perdían cada vez que cerrábamos una sesión de terminal, para que esto no pase, los añadimos también al archivo de configuración `.bashrc`. Por ejemplo, en mi caso he añadido las siguientes líneas

```
alias ll='ls -l'
alias la='ls -a'
alias lh='ls -h'
alias lha='ls -lha'
```

## Comandos de búsqueda

### Búsqueda de binarios con `which`

El primer comando de búsqueda que vamos a ver es `which` que nos permite encontrar la ruta de los binarios

In [ ]:
!which python

/home/wallabot/anaconda3/bin/python


Sin embargo, si buscamos algo que no esté en alguna de las rutas del PATH, `which` no será capaz de decirnos la ruta

In [ ]:
!which cd

### Búsqueda de archivos con `find`

Para buscar un archivo con find tenemos que indicarle desde qué ruta queremos buscar el archivo, seguido del flag `-name` y el nombre del archivo que queremos buscar.

In [ ]:
!find ~ -name "2021-02-11-Introduccion-a-Python.ipynb"

/home/wallabot/Documentos/web/portafolio/posts/prueba/2021-02-11-Introduccion-a-Python.ipynb
/home/wallabot/Documentos/web/portafolio/posts/2021-02-11-Introduccion-a-Python.ipynb


Como vemos, está en su directorio más la copia que he creado en este notebook y la he guardado en la carpeta `prueba`

Una cosa muy poderosa de `find` es que podemos usar `wildcards`, por ejemplo si quiero buscar todos los archivos de texto de mi carpeta `web`.

In [ ]:
!find ~/Documentos/web/ -name *.txt

/home/wallabot/Documentos/web/portafolio/posts/2022-09-12 Introduccion a la terminal.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/lista.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/dot.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/dot2.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/secuential.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/mitexto.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/file.txt
/home/wallabot/Documentos/web/wordpress_api_rest/page.txt


Si no queremos que distinga entre mayúsculas y minúsculas debemos usar el flag `-iname`, por ejemplo si buscamos todos los archivos que contengan el texto `FILE`, pero usando el flag `-iname`

In [ ]:
!find ~/Documentos/web/ -iname *FILE*

/home/wallabot/Documentos/web/portafolio/posts/html_files
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/file.txt


Vemos que todos los resultados contienen `file` y no `FILE`, es decir, no ha hecho distinción entre mayúsculas y minúsculas

Podemos especificar el tipo de archivo con el flag `-type`. Solo admite dos tipos `f` para archivos y `d` para directorios

In [ ]:
!find ~/Documentos/nerf -name image*

/home/wallabot/Documentos/nerf/instant-ngp/configs/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/benchmarks/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/cutlass/media/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/fmt/doc/bootstrap/mixins/image.less
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/data/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/dlss/NVIDIAImageScaling/samples/media/images
/home/wallabot/Documentos/nerf/instant-ngp/data/nerf/fox/images
/home/wallabot/Documentos/nerf/instant-ngp/data/image


In [ ]:
!find ~/Documentos/nerf -name image* -type d

/home/wallabot/Documentos/nerf/instant-ngp/configs/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/benchmarks/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/cutlass/media/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/data/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/dlss/NVIDIAImageScaling/samples/media/images
/home/wallabot/Documentos/nerf/instant-ngp/data/nerf/fox/images
/home/wallabot/Documentos/nerf/instant-ngp/data/image


In [ ]:
!find ~/Documentos/nerf -name image* -type f

/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/fmt/doc/bootstrap/mixins/image.less


Si queremos filtrar por el tamaño del archivo podemos usar el flag `-size`, por ejemplo, si queremos buscar todos los archivos de más de 200 MB

In [ ]:
!find ~/Documentos/ -type f -size +200M

/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_best_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/efficientnet-b7-dcc49843.pth
/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_best_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_best_model.pth


Si queremos realizar operaciones tras la búsqueda, usamos el flag `-exec`

Por ejemplo, voy a buscar todas las carpetas con el nombre `subdirectorio`

In [ ]:
!find ~/ -name subdirectorio -type d

/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio


Puedo hacer que se borren con el flag `-exec`

In [ ]:
!find ~/ -name subdirectorio -type d -exec rm -r {} \;

rm: ¿borrar el fichero regular vacío '/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt'  protegido contra escritura? (s/n) s
find: ‘/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio’: No existe el archivo o el directorio


In [ ]:
!find ~/ -name subdirectorio -type d

Por último, si usamos el carácter `!` estaremos indicando que encuentre todo lo que no coincide con lo que hemos especificado

In [ ]:
!find ~/Documentos/web/portafolio/posts/prueba ! -name *.txt

/home/wallabot/Documentos/web/portafolio/posts/prueba
/home/wallabot/Documentos/web/portafolio/posts/prueba/index.html
/home/wallabot/Documentos/web/portafolio/posts/prueba/Abc
/home/wallabot/Documentos/web/portafolio/posts/prueba/datos1
/home/wallabot/Documentos/web/portafolio/posts/prueba/2021-02-11-Introduccion-a-Python.ipynb
/home/wallabot/Documentos/web/portafolio/posts/prueba/datos123


Como vemos, ha encontrado todo lo que no es un `.txt`

## Comando de búsqueda `grep`

`grep` es un comando de búsqueda muy potente, por eso le dedicamos un apartado a él solo. El comando `grep` utiliza las expresiones regulares, por lo que si quieres aprender de ellas te dejo un enlace a un [post](https://maximofn.com/expresiones-regulares) donde las explico

Vamos a empezar a ver la potencia de este comando, vamos a buscar todas las veces que aparece el texto `MaximoFN` dentro del archivo `2021-02-11-Introduccion-a-Python.ipynb`

In [ ]:
terminal("cd /home/wallabot/Documentos/web/portafolio/posts/prueba")

In [ ]:
terminal("grep MaximoFN 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

        "a = 'MaximoFN'\n",
              "'MaximoFN'"
        "string = \"MaximoFN\"\n",
              "'MaximoFN'"
        "string = 'MaximoFN'\n",
              "'MaximoFN'"
            "Este es el blog de \"MaximoFN\"\n"
        "print(\"Este es el blog de \\\"MaximoFN\\\"\")"
            "Este es el blog de 'MaximoFN'\n"
        "print('Este es el blog de \\'MaximoFN\\'')"
            "Este es el blog de \\MaximoFN\\\n"
        "print('Este es el blog de \\\\MaximoFN\\\\')"
            "MaximoFN\n"
        "print('Este es el blog de \\nMaximoFN')"
            "Este es el blog de MaximoFN\n"
        "print('Esto no se imprimirá \\rEste es el blog de MaximoFN')"
            "Este es el blog de \tMaximoFN\n"
        "print('Este es el blog de \\tMaximoFN')"
            "Este es el blog deMaximoFN\n"
        "print('Este es el blog de \\bMaximoFN')"
	 ...
        "funcion2_del_modulo('MaximoFN')"
            "MaximoFN\n",
        "  print('MaximoFN')\n",
        "  variable = 'MaximoF

Sin embargo, si hacemos la misma búsqueda para el texto `maximofn`

In [ ]:
!grep maximofn 2021-02-11-Introduccion-a-Python.ipynb

No aparece ningún resultado, esto es porque `grep` es `case sensitive`, es decir, busca el texto tal cual se lo has introducido, diferenciando mayúsculas y minúsculas. Si no queremos esto, tenemos que introducir el flag `-i`

In [ ]:
terminal("grep -i MaximoFN 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

        "a = 'MaximoFN'\n",
              "'MaximoFN'"
        "string = \"MaximoFN\"\n",
              "'MaximoFN'"
        "string = 'MaximoFN'\n",
              "'MaximoFN'"
            "Este es el blog de \"MaximoFN\"\n"
        "print(\"Este es el blog de \\\"MaximoFN\\\"\")"
            "Este es el blog de 'MaximoFN'\n"
        "print('Este es el blog de \\'MaximoFN\\'')"
            "Este es el blog de \\MaximoFN\\\n"
        "print('Este es el blog de \\\\MaximoFN\\\\')"
            "MaximoFN\n"
        "print('Este es el blog de \\nMaximoFN')"
            "Este es el blog de MaximoFN\n"
        "print('Esto no se imprimirá \\rEste es el blog de MaximoFN')"
            "Este es el blog de \tMaximoFN\n"
        "print('Este es el blog de \\tMaximoFN')"
            "Este es el blog deMaximoFN\n"
        "print('Este es el blog de \\bMaximoFN')"
	 ...
        "funcion2_del_modulo('MaximoFN')"
            "MaximoFN\n",
        "  print('MaximoFN')\n",
        "  variable = 'MaximoF

Si lo que queremos es que nos devuelva el número de veces que aparece, introducimos el flag `-c`

In [ ]:
!grep -c MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

105


Si nos da igual si aparece con mayúscula o minúscula, podemos volver a agregar el flag `-i`, pero no hace falta meterlo separado del flag `-c`, se pueden introducir juntos

In [ ]:
!grep -ci MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

105


Si ahora queremos todas las veces en las que **no** aparece la palabra `MáximoFN` introducimos el flag `-v`

In [ ]:
!grep -cv MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

11573


## Utilidades de red

### Información de las interfaces de red con `ifconfig`

El primer comando va a ser `ifconfig` que nos muestra información de nuestras interfaces de red.

In [ ]:
!ifconfig

br-470e52ae2708: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:ac:d0:b9:eb  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:5d:15:1c:e9  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.144  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7dc2:6944:3fbe:c18e  prefixlen 64  scopeid 0x20<link>
        ether 24:4b:fe:5

Como vemos tenemos la información de todas las interfaces de red de mi ordenador, pero si quiero saber solo la de una, se especifica añadiendo su nombre

In [ ]:
!ifconfig enp6s0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.144  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7dc2:6944:3fbe:c18e  prefixlen 64  scopeid 0x20<link>
        ether 24:4b:fe:5c:f6:59  txqueuelen 1000  (Ethernet)
        RX packets 144467  bytes 123842258 (123.8 MB)
        RX errors 0  dropped 2060  overruns 0  frame 0
        TX packets 100786  bytes 55749109 (55.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



### Información de las interfaces de red con `ip`

Otra manera de obtener la información de nuestras interfaces de red es mediante el comando `ip`, añadiendo `a` nos da la información de todas las interfaces

In [ ]:
!ip a

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 24:4b:fe:5c:f6:59 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.144/24 brd 192.168.1.255 scope global dynamic noprefixroute enp6s0
       valid_lft 80218sec preferred_lft 80218sec
    inet6 fe80::7dc2:6944:3fbe:c18e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp5s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 4c:77:cb:1d:66:cc brd ff:ff:ff:ff:ff:ff
4: br-470e52ae2708: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:a

### Test de comunicaciones con `ping`

Otro comando útil es `ping`, que nos puede servir para ver si tenemos conexión con una determinada `IP`. Por ejemplo, la `IP` de Google es `142.250.200.78`, por lo que le hacemos `ping` a ver si nos contesta. El comando `ping` en Linux hace `ping`s sin parar, por lo que nunca termina hasta que no lo paramos, para que no pase eso añadimos el flag `-c` y el número de intentos

In [ ]:
!ping 142.250.200.132 -c 4

PING 142.250.200.132 (142.250.200.132) 56(84) bytes of data.
64 bytes from 142.250.200.132: icmp_seq=1 ttl=117 time=3.46 ms
64 bytes from 142.250.200.132: icmp_seq=2 ttl=117 time=3.77 ms
64 bytes from 142.250.200.132: icmp_seq=3 ttl=117 time=2.81 ms
64 bytes from 142.250.200.132: icmp_seq=4 ttl=117 time=2.86 ms

--- 142.250.200.132 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 2.812/3.227/3.773/0.405 ms


Lo mismo hubiera pasado si lo hubiéramos hecho directamente sobre `google.com`

In [ ]:
!ping www.google.com -c 4

PING www.google.com (142.250.200.132) 56(84) bytes of data.
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=1 ttl=117 time=2.74 ms
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=2 ttl=117 time=3.96 ms
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=3 ttl=117 time=3.56 ms
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=4 ttl=117 time=2.87 ms

--- www.google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 2.741/3.283/3.962/0.499 ms


### Descargar archivos fuente con `curl`

Podemos obtener un archivo de texto de una dirección dada mediante el comando `curl`, por ejemplo, nos podemos descargar el html de Google

In [ ]:
!curl https://www.google.com

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="es"><head><meta content="Google.es permite acceder a la informaci�n mundial en castellano, catal�n, gallego, euskara e ingl�s." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="zXcc4tMJWBRoE7q_o_Z2fQ">(function(){window.google={kEI:'M5GOY6PeLr-jkdUP1pir0AE',kEXPI:'0,1359409,6059,206,4804,2316,383,246,5,5367,1123753,1197713,688,380089,16115,28684,22430,1362,12312,17587,4998,13228,3847,10622,22741,5081,1593,1279,2742,149,1103,840,1983,214,4100,3514,606,2023,2297,14670,3227,2845,7,4773,28997,1850,15757,3,346,230,6459,149,13975,4,1528,2304,7039,27731,7357,13658,4437,16786,5815,2542,4094,4052,3,3541,1,14262,27892,2,14022,6248,19490,5680,1021,2380,28741,4569,6255,23421,1252,5835,14967,4333,7484,11406,15676,8155,7381,

También podemos hacer un pipeline para guardarlo en un archivo

In [ ]:
!curl https://www.google.com > google.html

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15168    0 15168    0     0   135k      0 --:--:-- --:--:-- --:--:--  137k


Ahora podemos ver si se ha guardado bien

In [ ]:
!cat google.html

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="es"><head><meta content="Google.es permite acceder a la informaci�n mundial en castellano, catal�n, gallego, euskara e ingl�s." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="Jo7WFU6XWWwu6NrdwaRyIw">(function(){window.google={kEI:'R5GOY-LZHLegkdUP_IqzoAE',kEXPI:'0,1359409,6059,206,4804,2316,383,246,5,5367,1123753,1197777,380713,16115,28684,22430,1362,283,12036,17580,4998,13228,516,3331,10622,22741,5081,1593,1279,2742,149,1103,840,1983,4,210,4100,3514,606,2023,2299,14668,3229,2843,7,4773,826,23475,4696,1851,15756,3,346,230,6459,149,13975,4,1528,2304,7039,20309,7422,7357,13658,4437,16786,5812,2545,4094,4052,3,3541,1,11943,30211,2,8984,1,5037,6249,19490,5679,1020,2378,28745,4568,6258,23418,1252,5835,14967,4333,4

### Descargar archivos con `wget`

Otro comando parecido es `wget`, sin embargo, a diferencia de `curl`, `wget` descarga el archivo directamente

In [ ]:
!wget https://www.google.com

--2022-12-06 01:49:19--  https://www.google.com/
Resolviendo www.google.com (www.google.com)... 142.250.200.68, 2a00:1450:4003:80c::2004
Conectando con www.google.com (www.google.com)[142.250.200.68]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/html]
Guardando como: “index.html.1”

index.html.1            [ <=>                ]  14,76K  --.-KB/s    en 0,002s  

2022-12-06 01:49:19 (7,17 MB/s) - “index.html.1” guardado [15117]



In [ ]:
!ls -l

total 316
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt


Vemos que lo ha guardado como `index.html`, que es como Google lo tiene nombrado

Si queremos que se guarde con un nombre específico podemos usar el flag `-O`

In [ ]:
!wget https://www.google.com -O google2.html

--2022-12-06 01:49:37--  https://www.google.com/
Resolviendo www.google.com (www.google.com)... 142.250.200.68, 2a00:1450:4003:80c::2004
Conectando con www.google.com (www.google.com)[142.250.200.68]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/html]
Guardando como: “google2.html”

google2.html            [ <=>                ]  14,78K  --.-KB/s    en 0,003s  

2022-12-06 01:49:37 (5,27 MB/s) - “google2.html” guardado [15131]



In [ ]:
!ls -l

total 332
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt


### Depuración de la ruta con `traceroute`

Un comando muy útil es ver la ruta hasta un destino, para ello usamos `traceroute`, por ejemplo vamos a ver todos los sitios por los que tengo que pasar para conectarme a Google

In [ ]:
!traceroute www.google.com

traceroute to www.google.com (142.250.200.68), 64 hops max
  1   192.168.1.1  0,435ms  0,154ms  0,133ms 
  2   188.127.176.1  3,979ms  2,914ms  3,397ms 
  3   10.15.0.77  3,600ms  3,914ms  2,669ms 
  4   10.15.246.6  3,567ms  3,713ms  2,926ms 
  5   *  *  * 
  6   72.14.209.84  3,981ms  2,914ms  2,993ms 
  7   *  *  * 
  8   142.251.54.148  3,856ms  2,916ms  2,905ms 
  9   142.250.200.68  2,908ms  2,949ms  3,037ms 


### Depuración de la ruta con `mtr`

Otra herramienta de depuración es `mtr`, que es una versión mejorada de `traceroute`. Ofrece información de cada salto, como el tiempo de respuesta, el porcentaje de paquetes perdidos, etc.

In [ ]:
!mtr -n maximofn.com

wallabot (192.168.178.144)
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                              Packets               Pings
 Host                                                                       Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 192.168.178.1                                                            0.0%   345    0.3   0.3   0.3   0.3   0.0
 2. 192.168.0.1                                                              0.0%   344    0.8   1.1   1.1   1.1   0.0
 3. (waiting for reply)
 4. 10.183.52.41                                                             0.0%   344    2.8   2.5   2.5   2.5   0.0
 5. 172.29.0.161                                                            47.7%   344    2.3   3.1   3.1  23.1   0.0
 6. (waiting for reply)
 7. 193.149.1.97                                                             0.0%   344    3.6   3.6   3.6  38.6   0.0
 8. (waiting for reply)
 9. 185.

Como se puede ver en el salto 5 se pierde casi el 50 % de los paquetes, por lo que me serviría para llamar a mi compañía de teléfono y decirle que me intente enrutar por otro lado

### Nombre de nuestra máquina con `hostname`

Si queremos saber el nombre de nuestro equipo podemos usar `hostname`, lo cual es útil si queremos conectarnos a nuestra máquina desde otra.

In [ ]:
!hostname

wallabot


### Información de enlace de puerta predeterminada con `route -n`

Si queremos conocer nuestra puerta de enlace predeterminada usamos el comando `route -n`

In [ ]:
!route -n

Tabla de rutas IP del núcleo
Destino         Pasarela        Genmask         Indic Métric Ref    Uso Interfaz
0.0.0.0         192.168.1.1     0.0.0.0         UG    100    0        0 enp6s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enp6s0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-470e52ae2708
192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 enp6s0


### Información de la IP de un dominio con `nslookup`

Si queremos saber la IP de algún dominio, lo podemos saber mediante el comando `nslookup`

In [ ]:
!nslookup google.com

Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.185.14
Name:	google.com
Address: 2a00:1450:4003:808::200e



Esto nos dice que la IPv4 de Google es 172.217.168.174 y su IPv6 es 2a00:1450:4003:803::200e

### Información de nuestra red con `netstats`

El último comando de utilidad es `netstats`, este comando nos da el estado de nuestra red, además con el flag `-i` nos devuelve nuestras interfaces de red

In [ ]:
!netstat -i

Tabla de la interfaz del núcleo
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
br-470e5  1500        0      0      0 0             0      0      0      0 BMU
docker0   1500        0      0      0 0             0      0      0      0 BMU
enp6s0    1500   148385      0   2182 0        106135      0      0      0 BMRU
lo       65536    11674      0      0 0         11674      0      0      0 LRU
wlp5s0    1500        0      0      0 0             0      0      0      0 BMU


### Consultas DNS con `dig`

Con el comando `dig <dominio>` podemos hacer consultas DNS, por ejemplo, vamos a hacer una consulta a Google

In [ ]:
!dig google.com


; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20527
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		283	IN	A	142.250.184.14

;; Query time: 8 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: dom sep 24 01:32:07 CEST 2023
;; MSG SIZE  rcvd: 55



Se puede ver

``` bash
;; ANSWER SECTION:
google.com.		283	IN	A	142.250.184.14
```

Por lo que la consulta nos ha dado la IP de Google

Podemos hacerle la consulta a un servidor DNS en particular con `dig @<servidor DNS> <dominio>`

In [ ]:
!dig @1.1.1.1 google.com


; <<>> DiG 9.16.1-Ubuntu <<>> @1.1.1.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15633
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		190	IN	A	142.250.184.14

;; Query time: 8 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: dom sep 24 01:33:40 CEST 2023
;; MSG SIZE  rcvd: 44



Hemos hecho la misma consulta, pero se la hemos hecho al DNS de Cloudflare

## Comprimiendo archivos

Antes de comprimir y descomprimir vamos a ver qué vamos a comprimir, primero imprimimos nuestra ruta y listamos los archivos.

In [ ]:
!pwd; ls -l

/home/wallabot/Documentos/web/portafolio/posts/prueba
total 332
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt


Vamos a crear una nueva carpeta y a copiar todo lo que está dentro de la actual carpeta en ella

In [ ]:
!mkdir tocompress; cp * tocompress; ls -l

cp: -r not specified; omitting directory 'tocompress'
total 336
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 dic  6 01:52 tocompress


Como vemos se ha copiado todo menos la propia carpeta `tocompress` ya que no hemos puesto el flag `-r` en el comando `cp`. Pero lo que ha pasado es lo que queríamos

### Comprimir con `tar`

El primer comando que vamos a usar para comprimir es `tar` al que vamos a añadir el flag `-c` de compress, `-v` de verbose, para que nos vaya sacando qué está haciendo y el flag `-f` de file, y a continuación el nombre que queremos que tenga el archivo comprimido y el nombre del archivo que queremos comprimir

In [ ]:
!tar -cvf tocompress.tar tocompress

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [ ]:
!ls -l

total 676
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 348160 dic  6 01:53 tocompress.tar


Vemos que ha creado el archivo `tocompress.tar`

Ahora vamos a repetir el proceso, pero añadiendo el flag `-z`, esto lo que hace es comprimir en el formato `gzip`, que es un algoritmo de compresión más eficiente

In [ ]:
!tar -cvzf tocompress.tar.gz tocompress

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [ ]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz


Como se puede ver, el archivo `tocompress.tar` ocupa `340 kB`, mientras que el archivo `tocompress.tar.gz` ocupa solo `52 kB`

Ahora vamos a descomprimir los archivos, para descomprimir, se usa el mismo comando, solo que cambiando el flag `-c` por el flag `-x`

Primero borramos la carpeta original

In [ ]:
!rm -r tocompress

Descomprimimos

In [ ]:
!tar -xvf tocompress.tar

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [ ]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz


Hacemos lo mismo con el `gzip`

In [ ]:
!rm -r tocompress

In [ ]:
!tar -xvzf tocompress.tar.gz

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [ ]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz


### Comprimir con `zip`

Otro comando para comprimir el `zip`, para comprimir solo hay que añadirle el flag `-r` (recursive), el nombre que queremos que tenga el archivo comprimido y el archivo que queremos comprimir

In [ ]:
!zip -r tocompress.zip tocompress

  adding: tocompress/ (stored 0%)
  adding: tocompress/lista.txt (deflated 23%)
  adding: tocompress/dot.txt (stored 0%)
  adding: tocompress/google.html (deflated 56%)
  adding: tocompress/index.html (stored 0%)
  adding: tocompress/Abc (stored 0%)
  adding: tocompress/google2.html (deflated 56%)
  adding: tocompress/dot2.txt (stored 0%)
  adding: tocompress/secuential.txt (stored 0%)
  adding: tocompress/index.html.1 (deflated 56%)
  adding: tocompress/file.txt (stored 0%)
  adding: tocompress/datos1 (stored 0%)
  adding: tocompress/2021-02-11-Introduccion-a-Python.ipynb (deflated 85%)
  adding: tocompress/datos123 (stored 0%)


In [ ]:
!ls -lh

total 792K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz
-r

Para descomprimir se usa el comando `unzip` seguido del nombre del archivo que quiero descomprimir. Primero borramos la carpeta `tocompress`

In [ ]:
!rm -r tocompress

In [ ]:
!unzip tocompress.zip

Archive:  tocompress.zip
   creating: tocompress/
  inflating: tocompress/lista.txt    
 extracting: tocompress/dot.txt      
  inflating: tocompress/google.html  
 extracting: tocompress/index.html   
 extracting: tocompress/Abc          
  inflating: tocompress/google2.html  
 extracting: tocompress/dot2.txt     
 extracting: tocompress/secuential.txt  
  inflating: tocompress/index.html.1  
 extracting: tocompress/file.txt     
 extracting: tocompress/datos1       
  inflating: tocompress/2021-02-11-Introduccion-a-Python.ipynb  
 extracting: tocompress/datos123     


In [ ]:
!ls -lh

total 792K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz
-r

## Procesos en background y foreground

### Pausar un proceso y llevarlo al background con `CTRL+Z`

Cuando corremos un proceso en la terminal, este puede que no pare de ejecutarse y queramos seguir usando la terminal, para solucionar esto podemos llevarnos el proceso al background presionando `CTRL+z`

Por ejemplo, me puedo hacer un ping a mí mismo, sin especificar el número de intentos, por lo que esto se estará ejecutando hasta que pare el proceso presionando `CTRL+C`

In [ ]:
!ping localhost

PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.036 ms
^C
--- localhost ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5127ms
rtt min/avg/max/mdev = 0.024/0.027/0.036/0.004 ms


Sin embargo, si lo que queremos es parar un momento el proceso para poder seguir usando la terminal, hay que introducir `Ctrl+Z`

In [ ]:
!ping localhost

PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.020 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.017 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.021 ms
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.055 ms
^Z
[1]+  Detenido                ping localhost


Como se indica, el proceso ha sido detenido, no se está ejecutando mientras lo he llevado al background

### Ver los procesos en background con `jobs`

Para ver qué procesos están en el background, tenemos dos comandos, por un lado podemos usar `jobs`

In [ ]:
!jobs

jobs
[1]+  Detenido                ping localhost


Este comando nos da el proceso y el número de job, este número será el que deberemos usar para llevar el proceso al foreground

### Ver los procesos en background con `ps`

Otro comando que podemos usar es `ps` (processes)

In [ ]:
!ps

    PID TTY          TIME CMD
  16232 pts/3    00:00:00 bash
  17070 pts/3    00:00:00 ping
  18376 pts/3    00:00:00 ps


Este comando no solo nos da la información de los procesos que corren en background, sino de todos los procesos que están corriendo en la terminal.

Es importante recalcar que si abrimos una nueva terminal y usamos cualquiera de estos comandos no nos va a dar la información del ping, ya que lo ejecutamos en otra terminal

In [ ]:
!ps

    PID TTY          TIME CMD
  18993 pts/2    00:00:00 bash
  19290 pts/2    00:00:00 ps


Como vemos `jobs` no devuelve nada porque en esta terminal no hay ningún proceso en el background y `ps` solo nos devuelve la información de bash (la propia terminal) y el comando ps lanzado

### Llevar un proceso del background al foreground

Para llevar un proceso alforeground hay que usar el comando `fg`, si se quiere traer el último que se ha llevado al background solo con poner `fg` vale, sino hay que indicarle el número de job

Vamos a volver a ver los procesos que teníamos en el background

In [ ]:
!jobs

[1]+  Detenido                ping localhost


Nos podemos llevar este proceso al foreground solo escribiendo `fg` o indicándole el número de job mediante `fg %1`

In [ ]:
!fg %1

ping localhost
64 bytes from localhost (127.0.0.1): icmp_seq=7 ttl=64 time=0.032 ms
64 bytes from localhost (127.0.0.1): icmp_seq=8 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=9 ttl=64 time=0.045 ms
64 bytes from localhost (127.0.0.1): icmp_seq=10 ttl=64 time=0.035 ms
64 bytes from localhost (127.0.0.1): icmp_seq=11 ttl=64 time=0.031 ms


### Correr un proceso directamente en el background

Vamos a volver a lanzar ahora el navegador Firefox escribiendo `firefox` en la terminal y pulsar `CTRL+Z` para llevarlo al background

In [ ]:
!firefox

[GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
[2022-11-29T06:16:17Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update
^Z
[1]+  Detenido                firefox


Como vemos, pone que el proceso ha sido detenido, por lo que si ahora queremos navegar por Firefox no podemos, ya que está detenido.

Para poder lanzar Firefox y que esté en background para que no nos bloquee la terminal, hay que escribir un `&` al final del comando

In [ ]:
!firefox &

[1] 23663
$ [GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
[2022-11-29T06:19:40Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update

$


Ahora nos lanzamos Firefox, nos dice su número de job y se queda en el background ejecutándose

De hecho, si ahora miramos los procesos, podemos ver el estado de Firefox es *Ejecutando*

In [ ]:
!jobs

[1]+  Ejecutando              firefox &


### Terminar un proceso que está en background

Como tenemos Firefox corriendo en background, si queremos que termine, tenemos que usar `kill` y el número de job del proceso. Vamos a usar `jobs` para ver el número de job de Firefox

In [ ]:
!jobs

[1]+  Ejecutando              firefox &


Su número de trabajo es el 1, por lo que ponemos ese número para terminar el proceso.

In [ ]:
!kill %1

No nos responde nada, pero si volvemos a usar `jobs` para ver los procesos en el background

In [ ]:
!jobs

[1]+  Terminado               firefox


Vemos que nos dice que Firefox ha terminado, si volvemos a ejecutar `jobs` ya no aparecerá nada

In [ ]:
!jobs

## Procesos en background independientes de la terminal

Hasta ahora hemos visto cómo ejecutar procesos en background dependientes de la terminal, esto quiere decir, que is mandamos al background un procesos y cerramos la terminal, este mandará un mensaje de fin a todos los procesos que están en su background y terminarán

Pero hay veces que nos interesa que el proceso se quede en background, poder cerrar la terminal, abrir otra y recuperar ese proceso, para ello usaremos `tmux`, que es un multiplexor de terminales.

Es posible que venga instalada, por lo que para instalarla tienes que introducir lo siguiente

``` bash
sudo apt install tmux
```

Una vez instalada, podemos crear una nueva sesión de `tmux` mediante el `tmux new -s <name>`

``` bash
tmux new -s session1
```

Esto nos abrirá una nueva terminal, que en realidad es una sesión de `tmux`

Dentro de ella podemos lanzar un proceso, por ejemplo un `ping` a nosotros mismos

In [ ]:
!ping localhost

PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.019 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.031 ms


Podemos cerrar esa terminal

Si abrimos una nueva, podemos ver todas las sesiones de `tmux` abiertas con el comando `tmux ls`

In [ ]:
!tmux ls

session1: 1 windows (created Tue Nov 29 08:15:22 2022)


Y podemos entrar en una sesión mediante el comando `tmux`, seguido de `a` (attach), `-t` (tag) y el nombre de la sesión

In [ ]:
!tmux a -t session1

64 bytes from localhost (127.0.0.1): icmp_seq=146 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=147 ttl=64 time=0.022 ms
64 bytes from localhost (127.0.0.1): icmp_seq=148 ttl=64 time=0.026 ms
64 bytes from localhost (127.0.0.1): icmp_seq=149 ttl=64 time=0.013 ms
64 bytes from localhost (127.0.0.1): icmp_seq=150 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=151 ttl=64 time=0.019 ms


Como vemos, hemos recuperado el `ping` de antes

Cuando estamos dentro de una sesión, podemos salir de ella (matándola) escribiendo `CTRL+D` o escribiendo `exit`

## Manejo de procesos

Para manejar los procesos de nuestro sistema tenemos varias opciones

### Manejador de procesos `ps`

Como hemos visto antes `ps` nos da los procesos que están corriendo en nuestra terminal. Por ejemplo, ejecutamos un proceso en el background y vemos los procesos con `ps`

In [ ]:
!firefox &

[1] 50555


Vemos ahora los procesos

In [ ]:
!ps

    PID TTY          TIME CMD
  36660 pts/3    00:00:00 bash
  50555 pts/3    00:00:02 firefox
  50613 pts/3    00:00:00 Socket Process
  50635 pts/3    00:00:00 Privileged Cont
  50683 pts/3    00:00:00 WebExtensions
  50741 pts/3    00:00:00 Web Content
  50743 pts/3    00:00:00 Web Content
  50748 pts/3    00:00:00 Web Content
  50840 pts/3    00:00:00 ps


Una vez sepamos su PID, podemos matar el proceso

In [ ]:
!kill 50555

Vemos ahora los procesos

In [ ]:
!ps

    PID TTY          TIME CMD
  36660 pts/3    00:00:00 bash
  51132 pts/3    00:00:00 ps


Pero como hemos dicho, lo malo de `ps` es que solo muestra los procesos de su terminal

Para que nos muestre todos los procesos del sistema tenemos que añadir `aux`

In [ ]:
terminal("ps aux", max_lines_output=10)

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.2  0.0 169936 13172 ?        Ss   23:06   0:01 /sbin/init splash
root           2  0.0  0.0      0     0 ?        S    23:06   0:00 [kthreadd]
root           3  0.0  0.0      0     0 ?        I<   23:06   0:00 [rcu_gp]
root           4  0.0  0.0      0     0 ?        I<   23:06   0:00 [rcu_par_gp]
root           5  0.0  0.0      0     0 ?        I<   23:06   0:00 [netns]
root           7  0.0  0.0      0     0 ?        I<   23:06   0:00 [kworker/0:0H-events_highpri]
root           9  0.0  0.0      0     0 ?        I<   23:06   0:00 [kworker/0:1H-events_highpri]
root          10  0.0  0.0      0     0 ?        I<   23:06   0:00 [mm_percpu_wq]
root          11  0.0  0.0      0     0 ?        S    23:06   0:00 [rcu_tasks_rude_]
	 ...
wallabot   11094  0.0  0.2 1184730916 65900 ?    Sl   23:19   0:00 /opt/google/chrome/chrome --type=renderer --crashpad-handler-pid=5080 --enable-crash-reporter=, -

Ahora, si lo que quiero es buscar solo los procesos que esté ejecutando mi usuario, lo puedo hacer creando un `pipe` y buscando con `grep`

In [ ]:
!ps aux | grep wallabot

avahi        802  0.0  0.0   8536  3912 ?        Ss   23:06   0:00 avahi-daemon: running [wallabot.local]
wallabot    1153  0.0  0.0  19856 10624 ?        Ss   23:06   0:00 /lib/systemd/systemd --user
wallabot    1154  0.0  0.0 170004  3680 ?        S    23:06   0:00 (sd-pam)
wallabot    1159  0.1  0.0 2569384 22808 ?       S<sl 23:06   0:01 /usr/bin/pulseaudio --daemonize=no --log-target=journal
wallabot    1161  0.1  0.1 591424 37248 ?        SNsl 23:06   0:02 /usr/libexec/tracker-miner-fs
wallabot    1164  0.0  0.0 390744  8664 ?        SLl  23:06   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
wallabot    1168  0.0  0.0 166804  6616 tty2     Ssl+ 23:06   0:00 /usr/lib/gdm3/gdm-x-session --run-script env GNOME_SHELL_SESSION_MODE=ubuntu /usr/bin/gnome-session --systemd --session=ubuntu
wallabot    1173  0.0  0.0   8904  6012 ?        Ss   23:06   0:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
wallabot    1181  0

### Manejador de procesos `top`

Con `top` podemos ver todos los procesos del sistema operativo. Nos enseñará la información con `less`, por lo que, al igual que se ha explicado antes, cuando se quiera parar `top`, introduciendo `q` parará

In [ ]:
!top

top - 09:31:32 up  3:21,  1 user,  load average: 2,42, 2,79, 2,48
Tareas: 382 total,   1 ejecutar,  381 hibernar,    0 detener,    0 zombie
%Cpu(s): 14,2 usuario,  1,5 sist,  0,0 adecuado, 84,3 inact,  0,0 en espera,  0,
MiB Mem :  32006,4 total,  20281,8 libre,   6229,0 usado,   5495,6 búfer/caché
MiB Intercambio:   2048,0 total,   2048,0 libre,      0,0 usado.  24979,1 dispon

    PID USUARIO   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     HORA+ ORDEN    
  10192 wallabot  20   0 3347636 388848  84140 S 137,5   1,2 282:24.59 python   
  44161 wallabot  20   0   30,2g 217208 100148 S  12,5   0,7   0:40.92 spotify  
     76 root      20   0       0      0      0 S   6,2   0,0   0:00.12 ksoftir+ 
   1105 root     -51   0       0      0      0 S   6,2   0,0   2:54.29 irq/125+ 
  43990 wallabot  20   0 3998836 246260 145800 S   6,2   0,8   0:53.69 spotify  
  44101 wallabot  20   0 1995108 130316  89848 S   6,2   0,4   0:08.34 spotify  
  51510 wallabot  20   0   14876   4088   3288 R   

Como se puede ver, el `PID` 44161 es Spotify que lo estoy usando ahora para reproducir música, pero con `ps` no lo habíamos visto

Al igual que antes, si queremos matar un proceso debemos introducir `kill` y su `PID`

Lo bueno de top es que nos da muchas más utilidades, si pulsamos `h` nos mostrará ayuda

In [ ]:
!h

Help for Interactive Commands - procps-ng 3.3.16
Window 1:Def: Cumulative mode Apagado.  System: Delay 3,0 secs; Secure mode Apag

  Z,B,E,e   Global: 'Z' colors; 'B' bold; 'E'/'e' summary/task memory scale
  l,t,m     Toggle Summary: 'l' load avg; 't' task/cpu stats; 'm' memory info
  0,1,2,3,I Toggle: '0' zeros; '1/2/3' cpus or numa node views; 'I' Irix mode
  f,F,X     Fields: 'f'/'F' add/remove/order/sort; 'X' increase fixed-width

  L,&,<,> . Locate: 'L'/'&' find/again; Move sort column: '<'/'>' left/right
  R,H,J,C . Toggle: 'R' Sort; 'H' Threads; 'J' Num justify; 'C' Coordinates
  c,i,S,j . Toggle: 'c' Cmd name/line; 'i' Idle; 'S' Time; 'j' Str justify
  x,y     . Toggle highlights: 'x' sort field; 'y' running tasks
  z,b     . Toggle: 'z' color/mono; 'b' bold/reverse (only if 'x' or 'y')
  u,U,o,O . Filter by: 'u'/'U' effective/any user; 'o'/'O' other criteria
  n,#,^O  . Set: 'n'/'#' max tasks displayed; Show: Ctrl+'O' other filter(s)
  V,v     . Toggle: 'V' forest view; 'v' h

Para salir, pulsar `ESC` o `q`

Como se muestra en la ayuda, si se introduce `u` podemos filtrar por usuario, introducimos mi usuario (wallabot) y puedo ver solo mis procesos

In [ ]:
!u

top - 09:35:57 up  3:25,  1 user,  load average: 1,02, 2,27, 2,39
Tareas: 378 total,   1 ejecutar,  377 hibernar,    0 detener,    0 zombie
%Cpu(s): 13,4 usuario,  0,4 sist,  0,0 adecuado, 86,1 inact,  0,1 en espera,  0,
MiB Mem :  32006,4 total,  20288,0 libre,   6212,0 usado,   5506,4 búfer/caché
MiB Intercambio:   2048,0 total,   2048,0 libre,      0,0 usado.  24989,1 dispon

    PID USUARIO   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     HORA+ ORDEN    
  10192 wallabot  20   0 3347636 388848  84140 S 148,2   1,2 288:46.50 python   
  43990 wallabot  20   0 3998836 246552 146092 S   2,7   0,8   0:59.55 spotify  
   1384 wallabot  20   0 4909848 453700 133164 S   1,7   1,4  11:14.02 gnome-s+ 
   1119 wallabot   9 -11 3093876  24504  17836 S   1,3   0,1   0:48.99 pulseau+ 
  32462 wallabot  20   0 1134,0g 643412 128632 S   1,3   2,0   7:39.91 chrome   
  44161 wallabot  20   0   30,2g 217112 100488 S   1,3   0,7   0:44.87 spotify  
  10135 wallabot  20   0  826220  58164  41648 S   

Otra forma de ver esto para poder filtrar por usuario sería hacerse un pipeline y usando `grep`

In [ ]:
!top | grep wallabot

   1440 wallabot  20   0 4684708 505432 118024 S   6,7   1,5   2:05.92 gnome-s+ 
  25326 wallabot  20   0 1133,0g 527912 123732 S   1,7   1,6   1:31.73 chrome   
   1440 wallabot  20   0 4684708 505476 118024 S   1,3   1,5   2:05.96 gnome-s+ 
   6199 wallabot  20   0 1131,0g 266068 116164 S   0,3   0,8   0:15.23 chrome   
  17606 wallabot  20   0  818228  52096  39488 S   0,3   0,2   0:02.59 gnome-t+ 
  34284 wallabot  20   0   14876   4376   3308 R   0,3   0,0   0:00.02 top


### Manejador de procesos `htop`

Es parecido a `top` pero más potente

Probablemente no lo tengas instalado, así que para instalarlo introduce el comando

``` bash
sudo apt install htop
```

o

``` bash
sudo snap install htop
```

### Manejador de procesos `glances`

Es parecido a `top` pero más potente

Probablemente no lo tengas instalado, así que para instalarlo introduce el comando

``` bash
sudo apt install glances
```

## Gestión de memoria RAM

Si solo queremos obtener información de la memoria podemos hacer uso del comando `free`

In [ ]:
!free

              total       usado       libre  compartido búfer/caché  disponible
Memoria:    32774516     6563544    20091804      276296     6119168    25479600
Swap:       2097148           0     2097148


Pero como esta información no es muy fácil de digerir, añadimos el flag `-h` (human), para que sea más fácil de leer

In [ ]:
!free -h

              total       usado       libre  compartido búfer/caché  disponible
Memoria:        31Gi       6,3Gi        19Gi       270Mi       5,8Gi        24Gi
Swap:         2,0Gi          0B       2,0Gi


## Gestión del disco duro

Para obtener información del disco duro hacemos uso del comando `du`, si solo introducimos este comando por terminal nos dará la información de todas las carpetas de nuestra máquina, por eso, para no obtener demasiada información, es necesario introducirle una ruta que queremos escanear

In [ ]:
!du ~/Documentos/web/portafolio/posts/

8	/home/wallabot/Documentos/web/portafolio/posts/__pycache__
1648	/home/wallabot/Documentos/web/portafolio/posts/notebooks_translated
4288	/home/wallabot/Documentos/web/portafolio/posts/html_files
336	/home/wallabot/Documentos/web/portafolio/posts/prueba/tocompress
1132	/home/wallabot/Documentos/web/portafolio/posts/prueba
16	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python/__pycache__
28	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python
11232	/home/wallabot/Documentos/web/portafolio/posts/


Al igual que antes, añadimos el flag `-h` (human) para que sea más fácil de leer

In [ ]:
!du ~/Documentos/web/portafolio/posts/ -h

8,0K	/home/wallabot/Documentos/web/portafolio/posts/__pycache__
1,7M	/home/wallabot/Documentos/web/portafolio/posts/notebooks_translated
4,2M	/home/wallabot/Documentos/web/portafolio/posts/html_files
336K	/home/wallabot/Documentos/web/portafolio/posts/prueba/tocompress
1,2M	/home/wallabot/Documentos/web/portafolio/posts/prueba
16K	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python/__pycache__
28K	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python
11M	/home/wallabot/Documentos/web/portafolio/posts/


## Gestión de interfaces

En Ubuntu, por defecto arrancamos en una interfaz gráfica, pero podemos abrir otras interfaces, que no serán gráficas, introduciendo `CTRL`+`ALT`+`F<num>` donde el número puede ir desde el 1 hasta el 6. Solo la 2 tendrá la interfaz gráfica y la 1 será el inicio de sesión

Al manejar varias interfaces podemos no saber en cuál nos encontramos, así que introduciendo el comando `tty` nos dirá en cuál estamos

In [ ]:
!tty

/dev/pts/0


## Manejo de paquetes

### Repositorios PPA (Personal Package Archives)

En Linux, la gestión de paquetes se hace a través de repositorios. Esto es una lista de direcciones donde se encuentran los binarios de nuestros programas. Así, cuando queremos actualizar o instalar nuestros programas (luego explicaremos cómo), lo que hará el sistema operativo es ver la lista de estos repositorios e ir a las direcciones indicadas a buscar los binarios

Esta lista de repositorios se encuentra en `/etc/apt/sources.list` y dentro de la carpeta `/etc/apt/sources.list.d`. Vamos a ver esta lista.

In [ ]:
terminal("cat /etc/apt/sources.list", max_lines_output=10)

# deb cdrom:[Ubuntu 20.04.2.0 LTS _Focal Fossa_ - Release amd64 (20210209.1)]/ focal main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://es.archive.ubuntu.com/ubuntu/ focal main restricted
# deb-src http://es.archive.ubuntu.com/ubuntu/ focal main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://es.archive.ubuntu.com/ubuntu/ focal-updates main restricted
	 ...
deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
# deb-src https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
deb https://apt.kitware.com/ubuntu/ focal main
# deb-src https://apt.kitware.com/ubuntu/ focal main



Las primeras líneas que incluyen la palabra `cd-rom` son referencias al CD de instalación, siempre vienen con las palabras `deb cdrom:` aunque se haya instalado a través de la red o de un USB.

A partir de aquí empiezan a aparecer diversas líneas que empiezan con `deb` o `deb-src`. En `deb` se encuentran los binarios y en `deb-src` se encuentra el código fuente.

Toda dirección válida de repositorio tiene uno de estos formatos:

* deb http://dirección_del_servidor/nombre_carpeta nombre_de_versión (main o universe o multiverse o main restricted, etc)
* deb-src http://direccion_del_servidor/nombre_carpeta nombre_de_version (main o universe o multiverse o main restricted, etc)

Los seis tipos de repositorios de Ubuntu son:
 1. Main

El repositorio `Main` está activado por defecto y contiene solo software libre y de código abierto o `FOSS` por sus siglas en inglés (Free and Open-Source Software).

 2. Universe

Como `Main`, `Universe` también ofrece `FOSS`. La diferencia es que en este repositorio no es Ubuntu quien garantiza actualizaciones de seguridad regulares, sino que es la comunidad quien se encarga de su soporte. Viene activado por defecto, pero no siempre. Algunos sistemas operativos lo tienen desactivado por defecto y podríamos tener que activarlo si estamos ejecutando una Live Session. Si no lo tenemos añadido, podemos hacerlo con este comando:
    
``` bash
sudo add-apt-repository universe
```

¿Qué encontramos en «Universe»? Yo diría que la mayoría del software que merece la pena, entre lo que tenemos VLC u OpenShot.

 3. Multiverse

A partir de aquí vienen los repositorios de Ubuntu con menos libertad. `Multiverse` contiene software que ya no es `FOSS` y Ubuntu no puede activar este repositorio por defecto por problemas legales y de licencias. Por otra parte, tampoco puede proporcionar parches y actualizaciones. Con esto en mente, tenemos que valorar si lo añadimos o no, algo que podremos hacer con este comando:

``` bash
sudo add-apt-repository multiverse
```

 4. Restricted

En los repositorios de Ubuntu podremos encontrar software libre y de código abierto, pero esto no es posible cuando se trata de algo relacionado con el hardware. En los repositorios `Restricted` encontraremos drivers, como los de las tarjetas gráficas, paneles táctiles o tarjetas de red.

``` bash
sudo add-apt-repository restricted
```

5. Partner

Este repositorio contiene software propietario compilado por Ubuntu de sus socios.

 6. Repositorios de Ubuntu de terceros

Por último, tenemos los repositorios de terceros. Ubuntu trata de ofrecer siempre la mejor experiencia de usuario y ese es uno de los motivos por los que rechaza cierto software. También hay desarrolladores que prefieren tener un control total sobre lo que ofrecen y por ese motivo crean sus propios repositorios.

### Añadir repositorios

Si estamos en Ubuntu, podemos añadir un repositorio mediante el comando `add-apt-repository <repository>`. Pero como en otras distribuciones que no sean Ubuntu, no tenemos este comando

### Actualizar los repositorios

Mediante el comando `apt update` podremos actualizar las últimas versiones de los paquetes que tenemos en nuestro repositorio.

### Actualizar los paquetes

Mediante el comando `apt upgrade` podremos actualizar los programas que tengamos instalados y de los cuales antes hayamos actualizado su repositorio

### Actualizar el kernel

Si usamos el comando `apt dist-upgrade` se actualizarán también paquetes del kernel

> ¡Cuidado!: Actualizar paquetes del kernel puede conllevar a que algunos paquetes se rompan

> Recordatorio: Al actualizar paquetes del kernel, para que hagan efecto es necesario reiniciar el ordenador

### Búsqueda de paquetes

Con el comando `apt search <paquete>` podemos encontrar paquetes

In [ ]:
terminal("apt search vlc", max_lines_output=10)

Ordenando...
Buscar en todo el texto...
anacrolix-dms/focal 1.1.0-1 amd64
  Go UPnP DLNA Digital Media Server with basic video transcoding

cubemap/focal 1.4.3-1build1 amd64
  scalable video reflector, designed to be used with VLC

dvblast/focal 3.4-1 amd64
  Simple and powerful dvb-streaming application
	 ...

x264/focal 2:0.155.2917+git0a84d98-2 amd64
  video encoder for the H.264/MPEG-4 AVC standard




### Listado de paquetes instalados

Para ver qué paquetes tenemos instalados podemos usar `dpkg -l`, esto nos dará una lista de todos los paquetes que tenemos instalados en nuestro ordenador

In [ ]:
terminal("dpkg -l", max_lines_output=10)

Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                                     Versión                               Arquitectura Descripción
+++-==========================================-=====================================-============-===========================================================================================================================================================================================================================================================================================================================================================================================================================================
ii  accountsservice                            0.6.55-0ubuntu12~20.04.5              amd64        query and manipulate user account infor

Si queremos buscar si tenemos un paquete instalado, podemos usar el comando anterior y crear un `pipe` y buscar el nombre del paquete con `grep`

In [ ]:
terminal("dpkg -l | grep vlc")

Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre         Versión      Arquitectura Descripción
+++-==============-============-============-=================================
ii  grep           3.4-1        amd64        GNU grep, egrep and fgrep
ii  vlc            3.0.9.2-1    amd64        multimedia player and streamer



### Instalar paquetes descargados y no de repositorios

En algunas ocasiones, cuando te quieres instalar un programa, lo que hacen es que te dan un archivo `.deb`, por lo que, para instalarlo, usamos el comando `dpkg -i <file.deb>`

## Administrador de usuarios

### Información del usuario activo con `id`

Mediante el comando `id` puedo ver qué usuario soy

In [ ]:
!id

uid=1000(wallabot) gid=1000(wallabot) grupos=1000(wallabot),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare),998(docker)


Con este comando puedo ver mi `id`, la id de grupo `gid` y los grupos a los que pertenezco. Las distribuciones basadas en Debian a los usuarios se les da una id a partir de la 1000, mientras que al usuario root se le asigna la `id` 0

### Información del usuario activo con `whoami`

Otro comando para saber qué usuario soy es `whoami`

In [ ]:
!whoami

wallabot


### Archivo con la información de todos los usuarios

La información de los usuarios está en el archivo `/etc/passwd`

In [ ]:
terminal("cat /etc/passwd", max_lines_output=10)

root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
	 ...
sshd:x:126:65534::/run/sshd:/usr/sbin/nologin
nvidia-persistenced:x:127:135:NVIDIA Persistence Daemon,,,:/nonexistent:/usr/sbin/nologin
fwupd-refresh:x:128:136:fwupd-refresh user,,,:/run/systemd:/usr/sbin/nologin
glances:x:129:137::/var/lib/glances:/usr/sbin/nologin



### Cambiar la contraseña de un usuario

Si quiero cambiar la contraseña de un usuario hay que usar el comando `passwd <user> <password>`, si no se especifica el usuario, se cogerá lo que devuelva el comando `whoami`

### Crear usuarios con `useradd`

Para crear un nuevo usuario se usa el comando `useradd <user name>`, vamos a crear un nuevo usuario

In [ ]:
!sudo useradd usertest1

Vamos a ver si está en el archivo con todos los usuarios

In [ ]:
!cat /etc/passwd | grep usertest

usertest1:x:1001:1001::/home/usertest1:/bin/sh


Como vemos, se ha creado el usuario con la `id` 1001, la siguiente a la que tenía mi usuario wallabot, que era el último

Sin embargo, al crear este usuario no nos ha pedido que le asignemos una contraseña. Además, si miramos qué hay dentro de `home`

In [ ]:
!ls /home

wallabot


Solo está la carpeta del usuario `wallabot`, pero no la del usuario `test1`

### Crear usuarios con `adduser`

Por lo que vamos a ver otro comando para crear usuarios que sí pide una contraseña y sí crea una carpeta en `home`. Este comando es `adduser`

In [ ]:
!sudo adduser usertest2

[sudo] contraseña para wallabot: 
Añadiendo el usuario `usertest2' ...
Añadiendo el nuevo grupo `usertest2' (1002) ...
Añadiendo el nuevo usuario `usertest2' (1002) con grupo `usertest2' ...
Creando el directorio personal `/home/usertest2' ...
Copiando los ficheros desde `/etc/skel' ...
Nueva contraseña: 
Vuelva a escribir la nueva contraseña: 
passwd: contraseña actualizada correctamente
Cambiando la información de usuario para usertest2
Introduzca el nuevo valor, o presione INTRO para el predeterminado
	Nombre completo []: 
	Número de habitación []: 
	Teléfono del trabajo []: 
	Teléfono de casa []: 
	Otro []: 
¿Es correcta la información? [S/n] s


Si miramos en el archivo con todos los usuarios

In [ ]:
!cat /etc/passwd | grep usertest

usertest1:x:1001:1001::/home/usertest1:/bin/sh
usertest2:x:1002:1002:,,,:/home/usertest2:/bin/bash


Vemos que se ha creado el usuario `usertest2`

In [ ]:
!ls /home

usertest2  wallabot


Y vemos que se ha creado una carpeta para él en `home`

Para borrar un usuario hay que usar el comando `userdel <username>`

In [ ]:
!sudo userdel usertest1

In [ ]:
!sudo userdel usertest2

Vamos a ver si están en el archivo con todos los usuarios.

In [ ]:
!cat /etc/passwd | grep usertest

Vemos que ya no aparece nada, de hecho vemos el final de ese archivo.

In [ ]:
!tail /etc/passwd

geoclue:x:122:127::/var/lib/geoclue:/usr/sbin/nologin
pulse:x:123:128:PulseAudio daemon,,,:/var/run/pulse:/usr/sbin/nologin
gnome-initial-setup:x:124:65534::/run/gnome-initial-setup/:/bin/false
gdm:x:125:130:Gnome Display Manager:/var/lib/gdm3:/bin/false
wallabot:x:1000:1000:wallabot,,,:/home/wallabot:/bin/bash
systemd-coredump:x:999:999:systemd Core Dumper:/:/usr/sbin/nologin
sshd:x:126:65534::/run/sshd:/usr/sbin/nologin
nvidia-persistenced:x:127:135:NVIDIA Persistence Daemon,,,:/nonexistent:/usr/sbin/nologin
fwupd-refresh:x:128:136:fwupd-refresh user,,,:/run/systemd:/usr/sbin/nologin
glances:x:129:137::/var/lib/glances:/usr/sbin/nologin


## Hacer un usuario administrador

Primero vamos a crear un usuario nuevo, que al inicio no será administrador

In [ ]:
!sudo adduser noadmin

Añadiendo el usuario `noadmin' ...
Añadiendo el nuevo grupo `noadmin' (1001) ...
Añadiendo el nuevo usuario `noadmin' (1001) con grupo `noadmin' ...
Creando el directorio personal `/home/noadmin' ...
Copiando los ficheros desde `/etc/skel' ...
Nueva contraseña: 
Vuelva a escribir la nueva contraseña: 
passwd: contraseña actualizada correctamente
Cambiando la información de usuario para noadmin
Introduzca el nuevo valor, o presione INTRO para el predeterminado
	Nombre completo []: 
	Número de habitación []: 
	Teléfono del trabajo []: 
	Teléfono de casa []: 
	Otro []: 
¿Es correcta la información? [S/n] s


Vamos a ver a qué grupos está el usuario que acabamos de crear, para ello usamos el comando `groups <user>`

In [ ]:
!groups noadmin

noadmin : noadmin


Como vemos, solo está en el grupo `noadmin`, que es un grupo que se creó al crear el usuario

Vamos a ver a qué grupos pertenece mi usuario

In [ ]:
!groups wallabot

wallabot : wallabot adm cdrom sudo dip plugdev lpadmin lxd sambashare docker


Como vemos, mi usuario pertenece a varios grupos más, entre ellos a uno llamado `sudo`. Los usuarios que tengan acceso a este grupo tienen poderes de administrador, por lo que para que el nuevo usuario que hemos creado tenga estos poderes hay que añadirle al grupo `sudo`

Para añadir a un usuario a un grupo hay dos maneras: una es con el comando `gpasswd -a <user> <group>`

In [ ]:
!sudo gpasswd -a noadmin sudo

Añadiendo al usuario noadmin al grupo sudo


Vemos ahora a qué grupos pertenece el usuario `noadmin`

In [ ]:
!groups noadmin

noadmin : noadmin sudo


Como vemos, ya pertenece al grupo sudo, por lo que ya tendría poderes de administrador

Eliminamos al usuario `noadmin` del grupo `sudo` con el comando `gpasswd -d <user> <group>`

In [ ]:
!sudo gpasswd -d noadmin sudo

Eliminando al usuario noadmin del grupo sudo


Vemos que `noadmin` ya no pertenece al grupo `sudo`

In [ ]:
!groups noadmin

noadmin : noadmin


El segundo comando para añadir a un usuario a un grupo es `usermod -aG <group> <user>`

In [ ]:
!sudo usermod -aG sudo noadmin

Volvemos a ver a qué grupos pertenece el usuario `noadmin`

In [ ]:
!groups noadmin

noadmin : noadmin sudo


Sacamos al usuario `noadmin` del grupo `sudo` y lo borramos

In [ ]:
!sudo gpasswd -d noadmin sudo

Eliminando al usuario noadmin del grupo sudo


In [ ]:
!sudo userdel noadmin

## Historial de comandos

### `history`

Si en la terminal introducimos el comando `history`, vemos un historial de los comandos utilizados

In [ ]:
!history

 1009  docker build . nvidia/cuda
 1010  docker build --help
 1011  docker build --build-arg nvidia/cuda
 1012  docker build --build-arg [nvidia/cuda]
 1013  cd ../docker/
 1014  docker ps -a
 1015  docker rm boring_wescoff 
 1016  docker compose up -d
 1017  docker compose exec deepstream61 bash
 1018  cd ..
    ....
 1996  ps
 1997  ps aux
 1998  camerasIP.sh 
 1999  sudo su
 2000  sudo useradd usertest
 2001  sudo userdel usertest
 2002  sudo useradd usertest
 2003  sudo userdel usertest
 2004  sudo su
 2005  sudo apt install history
 2006  history
 2007  clear
 2008  history


Si queremos ejecutar uno de los comandos del historial, lo hacemos mediante `!<num command>`, por ejemplo, si quiero volver a ejecutar el comando 1996

In [ ]:
! !1996

    PID TTY          TIME CMD
   6610 pts/0    00:00:00 bash
  20826 pts/0    00:00:00 ps


### `reverse-i-search`

Una manera más refinada de buscar en el historial es introducir `CTRL`+`r`. Al hacer esto, aparecerá el siguiente mensaje en la consola

In [ ]:
!reverse-i-search)`':

De manera que según vayas escribiendo, irán apareciendo comandos que coincidan con lo que has introducido. Por ejemplo, si introduzco `if` me aparece la última vez que utilicé `ifconfig`.

Si volvemos a introducir `CTRL`+`r` irán apareciendo coincidencias más antiguas

### Eliminar comandos del historial

Hay comandos como `ls`, `cd`, `pwd` que no nos aporta mucho que estén en el historial, por lo que se puede configurar para que no se guarden en el historial. Para hacerlo modificamos el archivo `~/.bashrc` y añadimos la línea `HISTIGNORE="pwd:ls:cd"`

## Seguridad

### Firewall `ufw`

Ubuntu viene con el firewall `ufw` instalado, pero para comprobarlo usamos el siguiente comando

In [ ]:
!sudo ufw status

Estado: inactivo


Como vemos por defecto está inactivo, por lo que vamos a crear un conjunto de reglas. Por ejemplo vamos a empezar abriendo el puerto 22 (SSH), para ello usamos el comando `sudo allow <port> comment "<coment>"`, con el que abrimos un puerto y añadimos un comentario

In [ ]:
!sudo ufw allow 22 comment 'ssh'

Regla añadida
Regla añadida (v6)


Como vemos, ha abierto el puerto 22 para IPv4 e IPv6. Vamos ahora a activar `ufw` con el comando `ufw enable`

In [ ]:
!sudo ufw enable

El cortafuegos está activo y habilitado en el arranque del sistema


Si queremos ver las reglas que tenemos en el firewall usamos el comando `ufw status`

In [ ]:
!sudo ufw enable

Hasta                      Acción      Desde
-----                      ------      -----
22                         ALLOW       Anywhere                   # ssh
22 (v6)                    ALLOW       Anywhere (v6)              # ssh


También podemos decirle que nos muestre las reglas numeradas con el comando `ufw status numbered`

In [ ]:
!sudo ufw status numbered

Estado: activo

     Hasta                      Acción      Desde
     -----                      ------      -----
[ 1] 22                         ALLOW IN    Anywhere                   # ssh
[ 2] 22 (v6)                    ALLOW IN    Anywhere (v6)              # ssh


Como las tenemos numeradas podemos eliminar una mediante el comando `ufw delete <rule number>`, por lo que para borrar la regla para IPv6 hacemos

In [ ]:
!sudo ufw delete 2

Estado: activo

Borrando:
 allow 22 comment 'ssh'
¿Continuar con la operación (s|n)? s
Regla eliminada (v6)


Volvemos a ver el estado

In [ ]:
!sudo ufw status numbered

Estado: activo

     Hasta                      Acción      Desde
     -----                      ------      -----
[ 1] 22                         ALLOW IN    Anywhere                   # ssh


Vemos que efectivamente se ha eliminado la regla número 2.

Si queremos habilitar la conexión SSH desde una sola IP usamos el flag `from <IP>`

In [ ]:
!sudo ufw  allow from 192.168.1.103 proto tcp to any port 22 comment 'ssh ip'

Regla añadida


Volvemos a comprobar las reglas

In [ ]:
!sudo ufw status numbered

Estado: activo

     Hasta                      Acción      Desde
     -----                      ------      -----
[ 1] 22                         ALLOW IN    Anywhere                   # ssh
[ 2] 22/tcp                     ALLOW IN    192.168.1.103              # ssh ip


Si queremos borrar todas las reglas usamos el comando `reset`

In [ ]:
!sudo ufw reset

Estado: activo

Reiniciando todas las reglas a sus valores predeterminados instalados.
¿Continuar con la operación (s|n)? s
Respaldando «user.rules» en «/etc/ufw/user.rules.20221205_171730»
Respaldando «before.rules» en «/etc/ufw/before.rules.20221205_171730»
Respaldando «after.rules» en «/etc/ufw/after.rules.20221205_171730»
Respaldando «user6.rules» en «/etc/ufw/user6.rules.20221205_171730»
Respaldando «before6.rules» en «/etc/ufw/before6.rules.20221205_171730»
Respaldando «after6.rules» en «/etc/ufw/after6.rules.20221205_171730»


Volvemos a comprobar el estado

In [ ]:
!sudo ufw status numbered

Estado: inactivo


Vemos que ya no hay ninguna regla

Para desactivar el firewall usamos el comando `ufw disable`

In [ ]:
!sudo ufw disable

El cortafuegos está detenido y deshabilitado en el arranque del sistema


Volvemos a comprobar el estado

In [ ]:
!sudo ufw status

Estado: inactivo


### Auditoría de seguridad con `Lynis`

Para instalar Lynis tienes que usar el comando `sudo apt install lynis`

Para hacer una auditoría de tu sistema hay que usar el comando `lynis audit system`. Esto comienza a hacer un escaneo de todo el sistema y te lo reporta.

> No voy a mostrar el resultado del escaneo de mi sistema para no mostrar en internet mis vulnerabilidades

## Programación de comandos

### Programación de comandos periódicos con `cron`

Con el comando `cron` podemos programar comandos para que se ejecuten periódicamente. Para ello tenemos que editar el archivo `/etc/crontab`

In [ ]:
!cat /etc/crontab

# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / &&

Como se puede ver, en este archivo hay una serie de comandos que se ejecutan periódicamente. El formato de estos comandos es el siguiente

```
<minuto> <hora> <día del mes> <mes> <día de la semana> <usuario> <comando>
```



Para crear bien la fecha en la que quieres que se ejecute el comando, hay un montón de páginas online que te ayudan a escribirlo bien, como por ejemplo [crontab guru](https://crontab.guru/)

### Programación de comandos de una sola ejecución con `at`

Cuando queremos que en el futuro se ejecute un comando, pero no queremos que se haga periódicamente, sino que solo se haga una sola vez podemos usar el comando `at`. Por ejemplo, enciendes una máquina de Azure, o Amazon, por la que te cobran y quieres estar seguro que se va a apagar y no te va a llegar una sorpresa en la factura, puedes dejar programado que por la noche se apague. Así, aunque se te olvide apagarla, se apagará sola

Hacemos un `ls` a la carpeta `/tmp`

In [ ]:
!ls -l /tmp

total 60
-rw------- 1 wallabot wallabot    0 sep 24 08:51 config-err-QM3AAe
-rw-r--r-- 1 root     root     2049 sep 24 08:51 glances-root.log
drwx------ 2 wallabot wallabot 4096 sep 24 09:06 pyright-9853-BG3nXEXw0Tao
drwxrwxr-x 3 wallabot wallabot 4096 sep 24 09:06 python-languageserver-cancellation
drwx------ 3 root     root     4096 sep 24 08:51 snap-private-tmp
drwx------ 2 wallabot wallabot 4096 sep 24 08:51 ssh-mHjlSPPoqCp7
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-colord.service-rpjPri
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-fwupd.service-FzPoQf
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-geoclue.service-F6pMWi
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-ModemManager.service-Orf6Bi
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8

Ahora vamos a programar que se cree un archivo nuevo en `/tmp` dentro de 5 minutos

In [ ]:
!at 09:55 touch /tmp/at.txt

at> touch /tmp/at.txt
at> <EOT>
job 1 at Sun Sep 24 09:55:00 2023


Como vemos, hay que escribir `at <time>` y en la siguiente línea el comando que queremos que se ejecute

Vemos ahora los archivos que hay en `/tmp`

In [ ]:
!ls -l /tmp

total 60
-rw-rw-r-- 1 wallabot wallabot    0 sep 24 09:55 at.txt
-rw------- 1 wallabot wallabot    0 sep 24 08:51 config-err-QM3AAe
-rw-r--r-- 1 root     root     2049 sep 24 08:51 glances-root.log
drwx------ 2 wallabot wallabot 4096 sep 24 09:06 pyright-9853-BG3nXEXw0Tao
drwxrwxr-x 3 wallabot wallabot 4096 sep 24 09:06 python-languageserver-cancellation
drwx------ 3 root     root     4096 sep 24 08:51 snap-private-tmp
drwx------ 2 wallabot wallabot 4096 sep 24 08:51 ssh-mHjlSPPoqCp7
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-colord.service-rpjPri
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-fwupd.service-FzPoQf
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-geoclue.service-F6pMWi
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-ModemManager.service-Orf6Bi
drwx------ 3 root     roo

Como vemos, hay un `at.txt` que se ha creado a las 09:55

## Atajos de teclado

A continuación se muestran unos cuantos atajos de teclado útiles en el uso de la terminal
 * Ctrl+a: lleva el cursor al inicio de la línea de comandos.
 * Ctrl+e: lleva el cursor al final de la línea de comandos.
 * Ctrl+l: limpia la terminal, similar a lo que hace el comando `clear`.
* Ctrl+u: limpia desde la posición del cursor hasta el inicio de la línea. Si se está al final, limpia la línea entera.
* Ctrl+k: limpia desde la posición del cursor hasta el final de la línea. Si se está al inicio, limpia la línea entera.
 * Ctrl+h: hace lo mismo que la tecla backspace, borra el carácter inmediatamente anterior a la posición del cursor.
 * Ctrl+w: borra la palabra inmediatamente anterior al cursor.
 * Alt+d o Esc+d: borra la palabra siguiente después del cursor.
* Ctrl+p: establece la línea de comandos con el último comando introducido.
* Ctrl+r: inicia la búsqueda de comandos usados anteriormente, tecleando parte de un comando usados anteriores que hayamos realizado incluyendo las opciones y parámetros. Hecha una búsqueda pulsando de nuevo la combinación de teclas encontraremos coincidencias anteriores.
* Ctrl+c: termina el proceso que se esté ejecutando, útil para recuperar el control del sistema.
* Ctrl+d: sale de la terminal, similar al comando exit.
* Ctrl+z: suspende la ejecución del proceso que se está ejecutando y lo pone en segundo plano; con el comando fg, podremos volver a continuar su ejecución.
 * Ctrl+t: intercambia la posición de los dos caracteres antes del cursor, útil para corregir malos tecleos.
 * Esc+t: intercambia la posición de las dos palabras antes del cursor, útil para corregir malos tecleos.
 * Alt+f: mueve el cursor al inicio de la palabra siguiente de la línea, lo mismo que Ctrl+right en la terminal de GNOME.
 * Alt+b: mueve el cursor al inicio de la palabra anterior de la línea, lo mismo que Ctrl+left en la terminal de GNOME.
 * Tab: autocompleta comandos o rutas de directorios o archivos.
 * Ctrl+Shift+f: abre un diálogo para hacer una búsqueda de texto en la salida de la terminal.
* Ctrl+Shift+g: busca la siguiente ocurrencia de la búsqueda previa en la terminal.
 * Ctrl+Shift+h: busca la anterior ocurrencia de la búsqueda previa en la terminal.
* Ctrl+Shift+c: copia el texto seleccionado de la terminal al portapapeles.
* Ctrl+Shift+v: pega el texto del portapapeles en la línea de comandos.
* Up: establece en la línea de comandos el comando anterior del historial, igual que Ctrl+p.
* Down: establece en la línea de comandos el siguiente comando del historial.
* Left Mouse: selecciona líneas de texto de la terminal.
* Ctrl+Left Mouse: selecciona bloques de texto de la terminal.

## Sistema de carpetas en Linux

En la siguiente imagen podemos ver cómo es el sistema de carpetas en Linux

![carpetas_linux](https://pub-fb664c455eca46a2ba762a065ac900f7.r2.dev/carpetas_linux.webp)

Esta imagen ha sido sacada del [post](https://www.linkedin.com/posts/robercmorais_tienes-dudas-sobre-para-que-se-usa-cada-activity-7153521372156116992-jzOK/) de LinkedIn [Roberto Morais](https://www.linkedin.com/in/robercmorais/)

## Fricadas

### Te olvidaste de usar sudo

¿Nunca te ha pasado que has ido a usar un comando que tenías que ejecutarlo con `sudo`, pero te olvidaste de escribir `sudo`? Pues, después de recibir el correspondiente error, si haces `sudo !!` se ejecutará el comando anterior con `sudo`

In [ ]:
!apt update

Leyendo lista de paquetes... Hecho
E: No se pudo abrir el fichero de bloqueo «/var/lib/apt/lists/lock» - open (13: Permiso denegado)
E: No se pudo bloquear el directorio /var/lib/apt/lists/
W: Se produjo un problema al desligar el fichero /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permiso denegado)
W: Se produjo un problema al desligar el fichero /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permiso denegado)


Como se puede ver, al hacer `sudo update` nos da un error, pero si ahora ejecutamos `sudo !!` se ejecutará `sudo apt update`

In [ ]:
!sudo !!

[sudo] contraseña para wallabot: 


### Mensajes del kernel

Con el comando `dmesg` (display kernel ring buffer messages) podemos ver los mensajes del kernel. Por ejemplo, esto es muy útil para ver si se ha conectado un dispositivo USB, o para depurar errores HW de nuestro ordenador

In [ ]:
!dmesg | tail

[   35.812312] input: LogiOps Virtual Input as /devices/virtual/input/input33
[   35.916406] input: LogiOps Virtual Input as /devices/virtual/input/input34
[   36.002064] input: LogiOps Virtual Input as /devices/virtual/input/input35
[   63.879806] input: MX Master 3 as /devices/virtual/misc/uhid/0005:046D:B023.0006/input/input36
[   63.879931] logitech-hidpp-device 0005:046D:B023.0006: input,hidraw3: BLUETOOTH HID v0.15 Keyboard [MX Master 3] on 4c:77:cb:1d:66:d0
[   63.902120] logitech-hidpp-device 0005:046D:B023.0006: HID++ 4.5 device connected.
[   69.604899] input: MX Keys Keyboard as /devices/virtual/misc/uhid/0005:046D:B35B.0007/input/input37
[   69.605221] input: MX Keys Mouse as /devices/virtual/misc/uhid/0005:046D:B35B.0007/input/input38
[   69.606204] hid-generic 0005:046D:B35B.0007: input,hidraw4: BLUETOOTH HID v0.13 Keyboard [MX Keys] on 4c:77:cb:1d:66:d0
[  188.285030] input: T9 (AVRCP) as /devices/virtual/input/input40


Con el flag `--follow` podemos ver en tiempo real los nuevos mensajes que se vayan generando

In [ ]:
!dmesg --follow

[    0.000000] Linux version 5.15.0-84-generic (buildd@lcy02-amd64-005) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 (Ubuntu 5.15.0-84.93~20.04.1-generic 5.15.116)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.15.0-84-generic root=UUID=59002381-d88d-44a6-b83d-8c5a226ce058 ro quiet splash vt.handoff=7
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Hygon HygonGenuine
[    0.000000]   Centaur CentaurHauls
[    0.000000]   zhaoxin   Shanghai  
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
[    0.000000] BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x0000000009d01fff] usable
[    0.000000] BIOS-e820: [mem 0x0000000009d02000-0x0000000009ffffff] reserved
[    0.000000] BIOS-

^C


### Información del hardware

Con `lshw` podemos ver información del hardware de nuestro ordenador

In [ ]:
!lshw

AVISO: debería ejecutar este programa como superusuario.
wallabot                    
    descripción: Computer
    anchura: 64 bits
    capacidades: smp vsyscall32
  *-core
       descripción: Motherboard
       id físico: 0
     *-memory
          descripción: Memoria de sistema
          id físico: 0
          tamaño: 32GiB
...
          producto: PnP device PNP0501
          id físico: 6
          capacidades: pnp
          configuración: driver=serial
     *-pnp00:05
          producto: PnP device PNP0c02
          id físico: 7
          capacidades: pnp
          configuración: driver=system
AVISO: la salida puede ser incompleta o imprecisa, debería ejecutar este programa como superusuario.


### Cowsay

Hay un comando llamado `cowsay` al que le pasas como parámetro un texto y te dibuja una vaca diciendo ese texto.

Es posible que no lo tengas instalado, por lo que, para instalarlo, tienes que introducir el comando

``` bash
sudo apt install cowsay
```

In [ ]:
terminal("cowsay MaximoFN")

 __________
< MaximoFN >
 ----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||



Si le añades el flag `-f dragon` quien lo dice es un dragón.

In [ ]:
terminal("cowsay -f dragon MaximoFN")

 __________
< MaximoFN >
 ----------
      \                    / \  //\
       \    |\___/|      /   \//  \\
            /0  0  \__  /    //  | \ \    
           /     /  \/_/    //   |  \  \  
           @_^_@'/   \/_   //    |   \   \ 
           //_^_/     \/_ //     |    \    \
        ( //) |        \///      |     \     \
      ( / /) _|_ /   )  //       |      \     _\
    ( // /) '/,_ _ _/  ( ; -.    |    _ _\.-~        .-~~~^-.
  (( / / )) ,-{        _      `-.|.-~-.           .~         `.
 (( // / ))  '/\      /                 ~-. _ .-~      .-~^-.  \
 (( /// ))      `.   {            }                   /      \  \
  (( / ))     .----~-.\        \-'                 .~         \  `. \^-.
             ///.----..>        \             _ -~             `.  ^-`  ^-_
               ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                  /.-~



In [ ]:
terminal("cowsay -f dragon-and-cow MaximoFN")

 __________
< MaximoFN >
 ----------
                       \                    ^    /^
                        \                  / \  // \
                         \   |\___/|      /   \//  .\
                          \  /O  O  \__  /    //  | \ \           *----*
                            /     /  \/_/    //   |  \  \          \   |
                            @___@`    \/_   //    |   \   \         \/\ \
                           0/0/|       \/_ //     |    \    \         \  \
                       0/0/0/0/|        \///      |     \     \       |  |
                    0/0/0/0/0/_|_ /   (  //       |      \     _\     |  /
                 0/0/0/0/0/0/`/,_ _ _/  ) ; -.    |    _ _\.-~       /   /
                             ,-}        _      *-.|.-~-.           .~    ~
            \     \__/        `/\      /                 ~-. _ .-~      /
             \____(oo)           *.   }            {                   /
             (    (--)          .----~-.\        \-`          

## Limpieza

Como se ha creado la carpeta `prueba`, la borramos para dejar todo como lo encontramos.

In [ ]:
!rm -r prueba